export type CatalogProduct = {
  id: string;
  name: string;
  englishName: string;
  aliases: string[];
  number: string;
  maker: string;
  release: string;
  image: string;
  officialUrl: string;
  verified: boolean;
};

export const expandedProducts: CatalogProduct[] = [
  {
    id: "nendoroid-682",
    name: "넨도로이드 우즈마키 나루토",
    englishName: "Nendoroid Naruto Uzumaki",
    aliases: ["우즈마키 나루토","Naruto Uzumaki","나루토","Naruto Shippuden","naruto"],
    number: "682",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20160927/5981/41605/large/52b7d31543c162aca4cd08b4a0af2788.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3724",
    verified: true,
  },
  {
    id: "nendoroid-707",
    name: "넨도로이드 우치하 사스케",
    englishName: "Nendoroid Sasuke Uchiha",
    aliases: ["우치하 사스케","Sasuke Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "707",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20161201/6106/42712/large/f528bfe7d67015eabfb2a47788ffb308.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3844",
    verified: true,
  },
  {
    id: "nendoroid-724",
    name: "넨도로이드 하타케 카카시",
    englishName: "Nendoroid Kakashi Hatake",
    aliases: ["하타케 카카시","Kakashi Hatake","나루토","Naruto Shippuden","naruto"],
    number: "724",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20170113/6174/43173/large/b8b7c2377ac1eccd19b779344c17453a.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3912",
    verified: true,
  },
  {
    id: "nendoroid-820",
    name: "넨도로이드 우치하 이타치",
    englishName: "Nendoroid Itachi Uchiha",
    aliases: ["우치하 이타치","Itachi Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "820",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20170905/6710/47433/large/125d2ee25ad3ac94ddb7c33400838f81.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4437",
    verified: true,
  },
  {
    id: "nendoroid-833",
    name: "넨도로이드 하루노 사쿠라",
    englishName: "Nendoroid Sakura Haruno",
    aliases: ["하루노 사쿠라","Sakura Haruno","나루토","Naruto Shippuden","naruto"],
    number: "833",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20171003/6764/47908/large/f40efe8b240e9f158495135a976aa272.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4491",
    verified: true,
  },
  {
    id: "nendoroid-872",
    name: "넨도로이드 우즈마키 나루토 중국 전시회 Ver.",
    englishName: "Nendoroid Naruto Uzumaki: NARUTO Animation Exhibition in China Ver.",
    aliases: ["우즈마키 나루토 중국 전시회 Ver.","Naruto Uzumaki: NARUTO Animation Exhibition in China Ver.","나루토","Naruto Shippuden","naruto"],
    number: "872",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180306/7104/50684/large/3fb759ce66e686f40a861b83ed96787a.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4823",
    verified: true,
  },
  {
    id: "nendoroid-879",
    name: "넨도로이드 휴우가 히나타",
    englishName: "Nendoroid Hinata Hyuga",
    aliases: ["휴우가 히나타","Hinata Hyuga","나루토","Naruto Shippuden","naruto"],
    number: "879",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180123/7004/49780/large/f9920095a8e0e9b08ebf3be4fa6b8476.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4724",
    verified: true,
  },
  {
    id: "nendoroid-886",
    name: "넨도로이드 지라이야 & 가마분타 세트",
    englishName: "Nendoroid Jiraiya & Gamabunta Set",
    aliases: ["지라이야 & 가마분타 세트","Jiraiya & Gamabunta Set","나루토","Naruto Shippuden","naruto"],
    number: "886",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180511/7272/51908/large/3d612be69a5d5a0caa8f4ba108ea10eb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4988",
    verified: true,
  },
  {
    id: "nendoroid-956",
    name: "넨도로이드 가아라",
    englishName: "Nendoroid Gaara",
    aliases: ["가아라","Gaara","나루토","Naruto Shippuden","naruto"],
    number: "956",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180625/7379/52822/large/cfa518492423633c15305ec0e4da8248.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/5095",
    verified: true,
  },
  {
    id: "nendoroid-991",
    name: "넨도로이드 쿠로사키 이치고",
    englishName: "Nendoroid Ichigo Kurosaki",
    aliases: ["쿠로사키 이치고","Ichigo Kurosaki","블리치","BLEACH","bleach"],
    number: "991",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180831/7581/54256/large/0e28b01c432abbd36b0d1c0b3f966b7c.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/5297",
    verified: true,
  },
  {
    id: "nendoroid-1008",
    name: "넨도로이드 츠나데",
    englishName: "Nendoroid Tsunade",
    aliases: ["츠나데","Tsunade","나루토","Naruto Shippuden","naruto"],
    number: "1008",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180926/7639/54864/large/a27b71e9f4cbdff73367c4cb008a6a25.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/5355",
    verified: true,
  },
  {
    id: "nendoroid-1181",
    name: "넨도로이드 나라 시카마루",
    englishName: "Nendoroid Shikamaru Nara",
    aliases: ["나라 시카마루","Shikamaru Nara","나루토","Naruto Shippuden","naruto"],
    number: "1181",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190730/8644/62457/large/32e8e19556da68b0e092e9288215e8bb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6351",
    verified: true,
  },
  {
    id: "nendoroid-1193",
    name: "넨도로이드 카마도 탄지로",
    englishName: "Nendoroid Tanjiro Kamado",
    aliases: ["카마도 탄지로","Tanjiro Kamado","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1193",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190809/8675/62911/large/95348670e396509ffc374dadea387268.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6382",
    verified: true,
  },
  {
    id: "nendoroid-1194",
    name: "넨도로이드 카마도 네즈코",
    englishName: "Nendoroid Nezuko Kamado",
    aliases: ["카마도 네즈코","Nezuko Kamado","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1194",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190823/8726/63216/large/3680bc7a33285fd5039443272c4ab396.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6433",
    verified: true,
  },
  {
    id: "nendoroid-1199",
    name: "넨도로이드 히츠가야 토시로",
    englishName: "Nendoroid Toushiro Hitsugaya",
    aliases: ["히츠가야 토시로","Toushiro Hitsugaya","블리치","BLEACH","bleach"],
    number: "1199",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190910/8782/63546/large/e0d91353ed90f2c13dbfb0a8269919e9.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6489",
    verified: true,
  },
  {
    id: "nendoroid-1232",
    name: "넨도로이드 오로치마루",
    englishName: "Nendoroid Orochimaru",
    aliases: ["오로치마루","Orochimaru","나루토","Naruto Shippuden","naruto"],
    number: "1232",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20191031/8949/65218/large/56c06e0c0ffcbbab42a51ac21febd3e5.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6656",
    verified: true,
  },
  {
    id: "nendoroid-1273",
    name: "넨도로이드 우즈마키 나루토 육도선인 Ver.",
    englishName: "Nendoroid Naruto Uzumaki: Sage of the Six Paths Ver.",
    aliases: ["우즈마키 나루토 육도선인 Ver.","Naruto Uzumaki: Sage of the Six Paths Ver.","나루토","Naruto Shippuden","naruto"],
    number: "1273",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20191227/9142/66526/large/5410e7d7066f438fc7615238708c7ec8.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6849",
    verified: true,
  },
  {
    id: "nendoroid-1303",
    name: "넨도로이드 록 리",
    englishName: "Nendoroid Rock Lee",
    aliases: ["록 리","Rock Lee","나루토","Naruto Shippuden","naruto"],
    number: "1303",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200305/9331/68162/large/3b7d9441442b39e769ec20b72692ba42.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7038",
    verified: true,
  },
  {
    id: "nendoroid-1334",
    name: "넨도로이드 아가츠마 젠이츠",
    englishName: "Nendoroid Zenitsu Agatsuma",
    aliases: ["아가츠마 젠이츠","Zenitsu Agatsuma","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1334",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200501/9477/84478/large/14ba78df5b27688cb75fb8ffa9453a75.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7184",
    verified: true,
  },
  {
    id: "nendoroid-1354",
    name: "넨도로이드 휴우가 네지",
    englishName: "Nendoroid Neji Hyuga",
    aliases: ["휴우가 네지","Neji Hyuga","나루토","Naruto Shippuden","naruto"],
    number: "1354",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200521/9535/69930/large/e101de5204248d0b7f2e2366b731b12f.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7238",
    verified: true,
  },
  {
    id: "nendoroid-1361",
    name: "넨도로이드 하시비라 이노스케",
    englishName: "Nendoroid Inosuke Hashibira",
    aliases: ["하시비라 이노스케","Inosuke Hashibira","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1361",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200603/9605/70420/large/2a47b57d772d64e9cc392cdcfccf57c3.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7307",
    verified: true,
  },
  {
    id: "nendoroid-1373",
    name: "넨도로이드 사소리",
    englishName: "Nendoroid Sasori",
    aliases: ["사소리","Sasori","나루토","Naruto Shippuden","naruto"],
    number: "1373",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200609/9624/70668/large/d3ed147f8ec84c6d7e4bad48bb2d00b0.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7326",
    verified: true,
  },
  {
    id: "nendoroid-1408",
    name: "넨도로이드 토미오카 기유",
    englishName: "Nendoroid Giyu Tomioka",
    aliases: ["토미오카 기유","Giyu Tomioka","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1408",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200715/9778/71979/large/cf36f88cfcb8e2934010482322e6785f.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7480",
    verified: true,
  },
  {
    id: "nendoroid-1479",
    name: "넨도로이드 이타도리 유지",
    englishName: "Nendoroid Yuji Itadori",
    aliases: ["이타도리 유지","Yuji Itadori","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1479",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/7867/7617d3ea951443a2decb80f85020d067.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7867",
    verified: true,
  },
  {
    id: "nendoroid-1481",
    name: "넨도로이드 데이다라",
    englishName: "Nendoroid Deidara",
    aliases: ["데이다라","Deidara","나루토","Naruto Shippuden","naruto"],
    number: "1481",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200928/10144/75049/large/613dcccc241b49389098f09ce694a676.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7838",
    verified: true,
  },
  {
    id: "nendoroid-1506",
    name: "넨도로이드 후시구로 메구미",
    englishName: "Nendoroid Megumi Fushiguro",
    aliases: ["후시구로 메구미","Megumi Fushiguro","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1506",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/8107/7b3890ef646fad029de87b5d5bcf9e1e.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8107",
    verified: true,
  },
  {
    id: "nendoroid-1510",
    name: "넨도로이드 카마도 탄지로 최종선별 Ver.",
    englishName: "Nendoroid Tanjiro Kamado: Final Selection Ver.",
    aliases: ["카마도 탄지로 최종선별 Ver.","Tanjiro Kamado: Final Selection Ver.","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1510",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20201021/10258/77749/large/d5b87eb8438c93bf5a11b0f8801de835.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7952",
    verified: true,
  },
  {
    id: "nendoroid-1524",
    name: "넨도로이드 나미카제 미나토",
    englishName: "Nendoroid Minato Namikaze",
    aliases: ["나미카제 미나토","Minato Namikaze","나루토","Naruto Shippuden","naruto"],
    number: "1524",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20201118/10411/78083/large/cb341f9826b56a4a6226f8842a0e7d30.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8105",
    verified: true,
  },
  {
    id: "nendoroid-1528",
    name: "넨도로이드 고죠 사토루",
    englishName: "Nendoroid Satoru Gojo",
    aliases: ["고죠 사토루","Satoru Gojo","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1528",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/8185/xqzEit1jAG7Hu2839cgBhNeT45PLdvKb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8185",
    verified: true,
  },
  {
    id: "nendoroid-1541",
    name: "넨도로이드 렌고쿠 쿄쥬로",
    englishName: "Nendoroid Kyojuro Rengoku",
    aliases: ["렌고쿠 쿄쥬로","Kyojuro Rengoku","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1541",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20201221/10607/79376/large/252a9defd5a7cd4d55e65ee015a27111.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8301",
    verified: true,
  },
  {
    id: "nendoroid-1548",
    name: "넨도로이드 쿠기사키 노바라",
    englishName: "Nendoroid Nobara Kugisaki",
    aliases: ["쿠기사키 노바라","Nobara Kugisaki","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1548",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210106/10648/79537/large/d1505881b0821fb8d9a9a24e129f66ce.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8342",
    verified: true,
  },
  {
    id: "nendoroid-1560",
    name: "넨도로이드 덴지",
    englishName: "Nendoroid Denji",
    aliases: ["덴지","Denji","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "1560",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/8409/0FnUA4QcRW1zxDXLaqSVNPHYETy6r5m7.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8409",
    verified: true,
  },
  {
    id: "nendoroid-1569",
    name: "넨도로이드 사비토",
    englishName: "Nendoroid Sabito",
    aliases: ["사비토","Sabito","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1569",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210209/10789/81137/large/db427aa438e8915a685ac6d5f8eb99b8.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8483",
    verified: true,
  },
  {
    id: "nendoroid-1570",
    name: "넨도로이드 마코모",
    englishName: "Nendoroid Makomo",
    aliases: ["마코모","Makomo","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1570",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210209/10790/81169/large/1f150eb9bd62674d67d4d6d0cd85c984.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8484",
    verified: true,
  },
  {
    id: "nendoroid-1580",
    name: "넨도로이드 파워",
    englishName: "Nendoroid Power",
    aliases: ["파워","Power","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "1580",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210219/10834/81352/large/f85662773a3004d8c1397adb1d6d3507.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8528",
    verified: true,
  },
  {
    id: "nendoroid-1636",
    name: "넨도로이드 하타케 카카시 암부 Ver.",
    englishName: "Nendoroid Kakashi Hatake: Anbu Black Ops Ver.",
    aliases: ["하타케 카카시 암부 Ver.","Kakashi Hatake: Anbu Black Ops Ver.","나루토","Naruto Shippuden","naruto"],
    number: "1636",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210614/11348/86493/large/d999a1ac81939067d01ecf2a3cf5c1db.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9042",
    verified: true,
  },
  {
    id: "nendoroid-1655",
    name: "넨도로이드 코쵸우 시노부",
    englishName: "Nendoroid Shinobu Kocho",
    aliases: ["코쵸우 시노부","Shinobu Kocho","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1655",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210705/11453/86903/large/54ff64a0dcbe36d5a9e9bbff790dab3f.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9147",
    verified: true,
  },
  {
    id: "nendoroid-1726",
    name: "넨도로이드 우치하 이타치 암부 Ver.",
    englishName: "Nendoroid Itachi Uchiha: Anbu Black Ops Ver.",
    aliases: ["우치하 이타치 암부 Ver.","Itachi Uchiha: Anbu Black Ops Ver.","나루토","Naruto Shippuden","naruto"],
    number: "1726",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20211002/11851/91232/large/d1c4ad3371ae2e2f15f7ba79ae8fc950.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9540",
    verified: true,
  },
  {
    id: "nendoroid-1750",
    name: "넨도로이드 이누마키 토게",
    englishName: "Nendoroid Toge Inumaki",
    aliases: ["이누마키 토게","Toge Inumaki","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1750",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/9667/048e36562a362bb27bf002721a9dbce4.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9667",
    verified: true,
  },
  {
    id: "nendoroid-1766",
    name: "넨도로이드 옷코츠 유타 주술회전 0 Ver.",
    englishName: "Nendoroid Yuta Okkotsu: Jujutsu Kaisen 0 Ver.",
    aliases: ["옷코츠 유타 주술회전 0 Ver.","Yuta Okkotsu: Jujutsu Kaisen 0 Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1766",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20211124/12044/92446/large/553f382dc1ac69f6077c28810c5dd680.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9732",
    verified: true,
  },
  {
    id: "nendoroid-1767",
    name: "넨도로이드 고죠 사토루 주술회전 0 Ver.",
    englishName: "Nendoroid Satoru Gojo: Jujutsu Kaisen 0 Ver.",
    aliases: ["고죠 사토루 주술회전 0 Ver.","Satoru Gojo: Jujutsu Kaisen 0 Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1767",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20211124/12045/95226/large/70b5015f1120eb1df463685c6074d4a1.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9733",
    verified: true,
  },
  {
    id: "nendoroid-1768",
    name: "넨도로이드 게토 스구루 주술회전 0 Ver.",
    englishName: "Nendoroid Suguru Geto: Jujutsu Kaisen 0 Ver.",
    aliases: ["게토 스구루 주술회전 0 Ver.","Suguru Geto: Jujutsu Kaisen 0 Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1768",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20211124/12046/95166/large/c6d6c3ad5271df5fafa74acc3ea42bb1.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9734",
    verified: true,
  },
  {
    id: "nendoroid-1812",
    name: "넨도로이드 나나미 켄토",
    englishName: "Nendoroid Kento Nanami",
    aliases: ["나나미 켄토","Kento Nanami","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1812",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20220128/12289/94869/large/1f5d9e4f02d1059ce65869b6cb95abaf.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9977",
    verified: true,
  },
  {
    id: "nendoroid-1830",
    name: "넨도로이드 우즈이 텐겐",
    englishName: "Nendoroid Tengen Uzui",
    aliases: ["우즈이 텐겐","Tengen Uzui","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1830",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20220218/12366/95610/large/aa7426ba3477ed4cf1e81ab74c382a12.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/10054",
    verified: true,
  },
  {
    id: "nendoroid-1834",
    name: "넨도로이드 료멘 스쿠나",
    englishName: "Nendoroid Sukuna",
    aliases: ["료멘 스쿠나","Sukuna","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1834",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/10133/54b47cdea45592f2ed4e8e946ae5cb49.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/10133",
    verified: true,
  },
  {
    id: "nendoroid-1948",
    name: "넨도로이드 카마도 네즈코 각성 Ver.",
    englishName: "Nendoroid Nezuko Kamado (Demon Form Advancing Ver.)",
    aliases: ["카마도 네즈코 각성 Ver.","Nezuko Kamado (Demon Form Advancing Ver.)","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1948",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20220803/13073/104056/large/93ec09a2ed01bb7c29f834755a292950.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/10758",
    verified: true,
  },
  {
    id: "nendoroid-2003",
    name: "넨도로이드 하야카와 아키",
    englishName: "Nendoroid Aki Hayakawa",
    aliases: ["하야카와 아키","Aki Hayakawa","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "2003",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20221124/13591/107704/large/3ddad1fb92e197d92fae77d79d25aca0.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11276",
    verified: true,
  },
  {
    id: "nendoroid-2004",
    name: "넨도로이드 마키마",
    englishName: "Nendoroid Makima",
    aliases: ["마키마","Makima","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "2004",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20221124/13590/107696/large/e3eb1d64c721a98a7ce0ceba701fb209.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11275",
    verified: true,
  },
  {
    id: "nendoroid-2014",
    name: "넨도로이드 히가시야마 코베니",
    englishName: "Nendoroid Kobeni",
    aliases: ["히가시야마 코베니","Kobeni","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "2014",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/11308/d0c5pNWiY3C4QPnzLUyJhfEZ9x7eXMVk.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11308",
    verified: true,
  },
  {
    id: "nendoroid-2092",
    name: "넨도로이드 렌고쿠 센쥬로",
    englishName: "Nendoroid Senjuro Rengoku",
    aliases: ["렌고쿠 센쥬로","Senjuro Rengoku","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2092",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230313/14105/112836/large/23d249a8c56c8c99109a18a272896eaa.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11790",
    verified: true,
  },
  {
    id: "nendoroid-2112",
    name: "넨도로이드 아카자",
    englishName: "Nendoroid Akaza",
    aliases: ["아카자","Akaza","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2112",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230420/14296/114581/large/d6e5d7b661e861bf9da059e434b83bb4.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11981",
    verified: true,
  },
  {
    id: "nendoroid-2120",
    name: "넨도로이드 우치하 오비토",
    englishName: "Nendoroid Obito Uchiha",
    aliases: ["우치하 오비토","Obito Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "2120",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230612/14479/119394/large/16e3716df40f953e905034fddedfcfcf.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12164",
    verified: true,
  },
  {
    id: "nendoroid-2175",
    name: "넨도로이드 우치하 마다라",
    englishName: "Nendoroid Madara Uchiha",
    aliases: ["우치하 마다라","Madara Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "2175",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230511/14367/115236/large/36efb9ab8495e8357fb8f60930c65aeb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12052",
    verified: true,
  },
  {
    id: "nendoroid-2205",
    name: "넨도로이드 고죠 사토루 고등전문학교 Ver.",
    englishName: "Nendoroid Satoru Gojo: Tokyo Jujutsu High School Ver.",
    aliases: ["고죠 사토루 고등전문학교 Ver.","Satoru Gojo: Tokyo Jujutsu High School Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2205",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/12289/449e249d91b186e9841499ee5d07849c.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12289",
    verified: true,
  },
  {
    id: "nendoroid-2206",
    name: "넨도로이드 게토 스구루 고등전문학교 Ver.",
    englishName: "Nendoroid Suguru Geto: Tokyo Jujutsu High School Ver.",
    aliases: ["게토 스구루 고등전문학교 Ver.","Suguru Geto: Tokyo Jujutsu High School Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2206",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/12290/9a598dd473339b0e6a808bc6486a33ce.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12290",
    verified: true,
  },
  {
    id: "nendoroid-2217",
    name: "넨도로이드 칸로지 미츠리",
    englishName: "Nendoroid Mitsuri Kanroji",
    aliases: ["칸로지 미츠리","Mitsuri Kanroji","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2217",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230829/14890/120353/large/3b1fb0d4ef318a7784b92c7346838087.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12575",
    verified: true,
  },
  {
    id: "nendoroid-2218",
    name: "넨도로이드 토키토 무이치로",
    englishName: "Nendoroid Muichiro Tokito",
    aliases: ["토키토 무이치로","Muichiro Tokito","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2218",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230720/14689/118454/large/08c7397abd7fab662ff8b13b84e95711.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12374",
    verified: true,
  },
  {
    id: "nendoroid-2280",
    name: "넨도로이드 후시구로 토우지",
    englishName: "Nendoroid Toji Fushiguro",
    aliases: ["후시구로 토우지","Toji Fushiguro","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2280",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230927/15038/121755/large/2fa918d4a11397ee4ad2ebde13512a85.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12722",
    verified: true,
  },
  {
    id: "nendoroid-2290",
    name: "넨도로이드 쵸소우",
    englishName: "Nendoroid Choso",
    aliases: ["쵸소우","Choso","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2290",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/12832/ded498960587d15c502c42d3163c5886.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12832",
    verified: true,
  },
  {
    id: "nendoroid-2305",
    name: "넨도로이드 이에이리 쇼코 고등전문학교 Ver.",
    englishName: "Nendoroid Shoko Ieiri: Tokyo Jujutsu High School Ver.",
    aliases: ["이에이리 쇼코 고등전문학교 Ver.","Shoko Ieiri: Tokyo Jujutsu High School Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2305",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20231023/15112/122473/large/d3f4b3a7bad52c1abf8a52ed689b5fbb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12795",
    verified: true,
  },
  {
    id: "nendoroid-2436",
    name: "넨도로이드 우치하 시스이",
    englishName: "Nendoroid Shisui Uchiha",
    aliases: ["우치하 시스이","Shisui Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "2436",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/56499/xj81nygZwtRFrh5TN7943BHk6PVvupUM.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/56499",
    verified: true,
  },
  {
    id: "nendoroid-2440",
    name: "넨도로이드 고죠 사토루 정장 Ver.",
    englishName: "Nendoroid Satoru Gojo: Suit Ver.",
    aliases: ["고죠 사토루 정장 Ver.","Satoru Gojo: Suit Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2440",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/36214/gFVKNXMJfTAPeE289cnyaWRk3Y5qsBGS.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/36214",
    verified: true,
  },
  {
    id: "nendoroid-2441",
    name: "넨도로이드 게토 스구루 정장 Ver.",
    englishName: "Nendoroid Suguru Geto: Suit Ver.",
    aliases: ["게토 스구루 정장 Ver.","Suguru Geto: Suit Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2441",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/36215/vZ2SMAxwiQGBusVqc9mrKnPNWRzUHeX7.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/36215",
    verified: true,
  },
  {
    id: "nendoroid-2505",
    name: "넨도로이드 시나즈가와 겐야",
    englishName: "Nendoroid Genya Shinazugawa",
    aliases: ["시나즈가와 겐야","Genya Shinazugawa","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2505",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/34679/TripG7eHyP1jsUZNkm9Bt2nzbFguhRCQ.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/34679",
    verified: true,
  },
  {
    id: "nendoroid-2506",
    name: "넨도로이드 시나즈가와 사네미",
    englishName: "Nendoroid Sanemi Shinazugawa",
    aliases: ["시나즈가와 사네미","Sanemi Shinazugawa","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2506",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/35752/tD65FWEyzY0jniwTvbMmR4HPBUVL9Zh3.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/35752",
    verified: true,
  },
  {
    id: "nendoroid-2687",
    name: "넨도로이드 센쥬 하시라마",
    englishName: "Nendoroid Hashirama Senju",
    aliases: ["센쥬 하시라마","Hashirama Senju","나루토","Naruto Shippuden","naruto"],
    number: "2687",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/57420/9WhJEdjM82wzQ0LZx5eVukvCTmYt6a1c.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/57420",
    verified: true,
  },
  {
    id: "nendoroid-2865",
    name: "넨도로이드 레제",
    englishName: "Nendoroid Reze",
    aliases: ["레제","Reze","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "2865",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/62079/ZjBXGDJn7EgepLhRiaPCsSHf2rF6k8Ky.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/62079",
    verified: true,
  },
  {
    id: "nendoroid-2933",
    name: "넨도로이드 옷코츠 유타 사형 집행 Ver.",
    englishName: "Nendoroid Yuta Okkotsu: Execution Ver.",
    aliases: ["옷코츠 유타 사형 집행 Ver.","Yuta Okkotsu: Execution Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2933",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1139229/0A1yYgJLqk4HFS75u6C2EZTswjzpRWmf.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1139229",
    verified: true,
  },
  {
    id: "nendoroid-2977",
    name: "넨도로이드 이타도리 유지 사형 집행 Ver. 베이직",
    englishName: "Nendoroid Yuji Itadori: Execution Ver. [Basic]",
    aliases: ["이타도리 유지 사형 집행 Ver. 베이직","Yuji Itadori: Execution Ver. [Basic]","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2977",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1140616/tuEc07NGJB2LRTH9ek6gjmWCsPzKwFpZ.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1140616",
    verified: true,
  },
  {
    id: "nendoroid-3034",
    name: "넨도로이드 도우마",
    englishName: "Nendoroid Doma",
    aliases: ["도우마","Doma","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "3034",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1140601/3EqZA5kvNKHLCp180cBSPgws7XjMezhi.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1140601",
    verified: true,
  },
  {
    id: "nendoroid-3035",
    name: "넨도로이드 젠인 마키 사형 집행 Ver. 베이직",
    englishName: "Nendoroid Maki Zen'in: Execution Ver. [Basic]",
    aliases: ["젠인 마키 사형 집행 Ver. 베이직","Maki Zen'in: Execution Ver. [Basic]","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "3035",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1140617/4E2pQes8MUJBmW9YbcAS7gFPXNh6CfHG.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1140617",
    verified: true,
  },
  {
    id: "nendoroid-3041",
    name: "넨도로이드 레제 캐주얼 의상 Ver. 베이직",
    englishName: "Nendoroid Reze: Casual Outfit Ver. [Basic]",
    aliases: ["레제 캐주얼 의상 Ver. 베이직","Reze: Casual Outfit Ver. [Basic]","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "3041",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1141481/QD7mJqbSWKL8i6a5C39cX4ztH0TGpnEZ.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1141481",
    verified: true,
  }
];
