export type CatalogProduct = {
  id: string;
  name: string;
  englishName: string;
  aliases: string[];
  number: string;
  maker: string;
  release: string;
  image: string;
  officialUrl: string;
  verified: boolean;
  series?: string;
};

export const expandedProducts: CatalogProduct[] = [
  {
    id: "nendoroid-803",
    name: "넨도로이드 에도가와 코난",
    englishName: "Nendoroid Conan Edogawa",
    aliases: ["에도가와 코난", "코난", "Conan Edogawa", "명탐정 코난", "Detective Conan"],
    number: "803",
    maker: "Good Smile Company",
    release: "2019.01",
    image: "https://images.goodsmile.info/cgm/images/product/20170725/6607/46723/medium/d0a56438c32fc116a551749551edf193.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4335/Nendoroid%2BConan%2BEdogawa",
    verified: true,
  },
  {
    id: "nendoroid-730",
    name: "넨도로이드 트레이서 클래식 스킨 에디션",
    englishName: "Nendoroid Tracer: Classic Skin Edition",
    aliases: ["트레이서", "Tracer", "클래식 스킨", "Classic Skin", "오버워치", "Overwatch"],
    number: "730",
    maker: "Good Smile Company",
    release: "2017.08",
    image: "https://images.goodsmile.info/cgm/images/product/20170127/6214/43683/medium/1b31cd527045883f7a88a7e55358a243.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3951/Nendoroid%2BTracer%2BClassic%2BSkin%2BEdition",
    verified: true,
  },
  {
    id: "nendoroid-544",
    name: "넨도로이드 커비",
    englishName: "Nendoroid Kirby",
    aliases: ["커비", "Kirby", "별의 커비", "Kirby of the Stars"],
    number: "544",
    maker: "Good Smile Company",
    release: "2016.01 · 2021.09/2025.07 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20150828/5207/45988/medium/c2810525be9bef0559a35fae0d9f7b19.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/2974/Nendoroid%20Kirby",
    verified: true,
  },
  {
    id: "nendoroid-511",
    name: "넨도로이드 미카즈키 무네치카",
    englishName: "Nendoroid Mikazuki Munechika",
    aliases: ["미카즈키 무네치카", "미카즈키", "Mikazuki Munechika", "도검난무", "Touken Ranbu"],
    number: "511",
    maker: "ORANGE ROUGE",
    release: "2015.08 · 2021.08 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20150319/4903/32750/medium/933252d99fa1e1a33e2352908574ee37.jpg",
    officialUrl: "https://www.goodsmile.info/en/product/4903/Nendoroid%2BMikazuki%2BMunechika.html",
    verified: true,
  },
  {
    id: "nendoroid-518",
    name: "넨도로이드 카슈 키요미츠",
    englishName: "Nendoroid Kashu Kiyomitsu",
    aliases: ["카슈 키요미츠", "카슈", "Kashu Kiyomitsu", "도검난무", "Touken Ranbu"],
    number: "518",
    maker: "ORANGE ROUGE",
    release: "2015.09 · 2018.05 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20150424/4976/33305/medium/a605b79a2c38b4e239ac638c10720463.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/2753",
    verified: true,
  },
  {
    id: "nendoroid-525",
    name: "넨도로이드 코기츠네마루",
    englishName: "Nendoroid Kogitsunemaru",
    aliases: ["코기츠네마루", "Kogitsunemaru", "도검난무", "Touken Ranbu"],
    number: "525",
    maker: "ORANGE ROUGE",
    release: "2015.11",
    image: "https://images.goodsmile.info/cgm/images/product/20150522/5028/33765/medium/491fc36bc73f5ada147b5e7e849044a4.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/2805/Nendoroid%2BKogitsunemaru",
    verified: true,
  },
  {
    id: "nendoroid-524",
    name: "넨도로이드 우마루",
    englishName: "Nendoroid Umaru",
    aliases: ["우마루", "도마 우마루", "Umaru", "Umaru Doma", "건어물 여동생 우마루짱"],
    number: "524",
    maker: "Good Smile Company",
    release: "2015.08 · 2018.03 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20150518/5013/33578/medium/6d8c468924fa320c73de7eb9bf1dcaa0.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/2790/Nendoroid%20Umaru",
    verified: true,
  },
  {
    id: "nendoroid-425",
    name: "넨도로이드 레드",
    englishName: "Nendoroid Red",
    aliases: ["레드", "Red", "포켓몬", "Pokémon", "Pokemon"],
    number: "425",
    maker: "Good Smile Company",
    release: "2014.09 · 2017.06 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20140508/4413/28904/medium/676add2fca03a6c91c265efc2bda0f1f.jpg",
    officialUrl: "https://www.goodsmile.info/en/product/4413/Nendoroid%2BRed.html",
    verified: true,
  },
  {
    id: "nendoroid-283",
    name: "넨도로이드 아스나",
    englishName: "Nendoroid Asuna",
    aliases: ["아스나", "Asuna", "소드 아트 온라인", "Sword Art Online", "SAO"],
    number: "283",
    maker: "Good Smile Company",
    release: "2013.03 · 2013.12 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20121011/3710/20826/medium/275230ceb5bef6b2f8ef9e9670c41f22.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1540/Nendoroid%2BAsuna",
    verified: true,
  },
  {
    id: "nendoroid-284",
    name: "넨도로이드 아이언맨 마크 7 히어로즈 에디션",
    englishName: "Nendoroid Iron Man Mark 7: Hero's Edition",
    aliases: ["아이언맨", "아이언맨 마크 7", "Iron Man", "Iron Man Mark 7", "마블", "Marvel"],
    number: "284",
    maker: "Good Smile Company",
    release: "2013.03",
    image: "https://www.nendo.guide/get/image/284/0",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3711/",
    verified: true,
  },
  {
    id: "nendoroid-17",
    name: "넨도로이드 L",
    englishName: "Nendoroid L",
    aliases: ["L", "엘", "데스노트", "Death Note"],
    number: "17",
    maker: "Good Smile Company",
    release: "2007.09 · 2008.04 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20091023/623/951/large/299f36c4d5f09bfb7cb725c3d597927e.jpg",
    officialUrl: "https://www.goodsmile.info/en/product/623/Nendoroid%2BL.html",
    verified: true,
  },
  {
    id: "nendoroid-16",
    name: "넨도로이드 아사히나 미쿠루",
    englishName: "Nendoroid Mikuru Asahina",
    aliases: ["아사히나 미쿠루", "미쿠루", "Mikuru Asahina", "스즈미야 하루히의 우울"],
    number: "16",
    maker: "Good Smile Company",
    release: "2007.09",
    image: "https://images.goodsmile.info/cgm/images/product/20091023/362/307/large/c48f8494391057d814d1b4fa45829f64.jpg",
    officialUrl: "https://www.goodsmile.info/en/product/362/Nendoroid%2BMikuru%2BAsahina.html",
    verified: true,
  },
  {
    id: "nendoroid-33",
    name: "넨도로이드 하츠네 미쿠",
    englishName: "Nendoroid Hatsune Miku",
    aliases: ["하츠네 미쿠", "미쿠", "Hatsune Miku", "보컬로이드", "Vocaloid", "오리지널 미쿠"],
    number: "33",
    maker: "Good Smile Company",
    release: "2008.03 · 2010.10까지 다수 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20091023/258/11458/large/6ceafce1774a6afbdf773812f19b1b53.jpg",
    officialUrl: "https://www.goodsmile.info/en/product/258/Nendoroid%2BHatsune%2BMiku.html",
    verified: true,
  },
  {
    id: "nendoroid-77",
    name: "넨도로이드 세이버 릴리",
    englishName: "Nendoroid Saber Lily",
    aliases: ["세이버 릴리", "Saber Lily", "페이트", "Fate"],
    number: "77",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20100406/2842/9783/medium/34ed8d2302230e6163b012bca1274ccc.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/2842/",
    verified: true,
  },
  {
    id: "nendoroid-97",
    name: "넨도로이드 스노우 미쿠",
    englishName: "Nendoroid Snow Miku",
    aliases: ["스노우 미쿠", "설미쿠", "Snow Miku", "하츠네 미쿠", "Hatsune Miku"],
    number: "97",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20100630/2899/10593/medium/b339bc37e529e7ead14f71673ff48587.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/2899/",
    verified: true,
  },
  {
    id: "nendoroid-97-playtime",
    name: "넨도로이드 스노우 미쿠 즐거운 눈놀이 에디션",
    englishName: "Nendoroid Snow Miku: Snow Playtime Edition",
    aliases: ["스노우 미쿠 눈놀이", "즐거운 눈놀이", "Snow Miku Snow Playtime", "설미쿠"],
    number: "97",
    maker: "Good Smile Company",
    release: "구판 확장판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20120125/3452/17050/medium/cf48eee0f23a9e95fa1e7c12b4be8f78.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3452/",
    verified: true,
  },
  {
    id: "nendoroid-106",
    name: "넨도로이드 블랙 록 슈터",
    englishName: "Nendoroid Black Rock Shooter",
    aliases: ["블랙 록 슈터", "Black Rock Shooter", "BRS"],
    number: "106",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20110106/3064/12542/medium/471cd79f1af768193dd0c831cb0a2d0b.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3064/",
    verified: true,
  },
  {
    id: "nendoroid-128",
    name: "넨도로이드 데드 마스터",
    englishName: "Nendoroid Dead Master",
    aliases: ["데드 마스터", "Dead Master", "블랙 록 슈터", "BRS"],
    number: "128",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20110808/3249/14935/medium/a767794b19c588bec8b01db7dee14b00.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3249/",
    verified: true,
  },
  {
    id: "nendoroid-129",
    name: "넨도로이드 하츠네 미쿠 앱솔루트 HMO 에디션",
    englishName: "Nendoroid Hatsune Miku: Absolute HMO Edition",
    aliases: ["미쿠 HMO", "앱솔루트 HMO", "Absolute HMO", "하츠네 미쿠", "Hatsune Miku"],
    number: "129",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20110808/3251/14949/medium/b0af4d0e854ede4344000ef0fc483a47.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3251/",
    verified: true,
  },
  {
    id: "nendoroid-143",
    name: "넨도로이드 블랙 골드 소",
    englishName: "Nendoroid Black Gold Saw",
    aliases: ["블랙 골드 소", "Black Gold Saw", "BGS", "블랙 록 슈터"],
    number: "143",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20110802/3241/14873/medium/0b41e35d33a2d8c8fd4f2ff83079ad57.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3241/",
    verified: true,
  },
  {
    id: "nendoroid-144",
    name: "넨도로이드 코우사카 키리노",
    englishName: "Nendoroid Kirino Kousaka",
    aliases: ["코우사카 키리노", "키리노", "Kirino Kousaka", "내 여동생이 이렇게 귀여울 리가 없어"],
    number: "144",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20120528/3561/18585/medium/5ee32bc57175ff1a5b62ca9a3cf420d8.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3561/",
    verified: true,
  },
  {
    id: "nendoroid-163",
    name: "넨도로이드 쿠로네코",
    englishName: "Nendoroid Kuroneko",
    aliases: ["쿠로네코", "Kuroneko", "고코우 루리", "내 여동생이 이렇게 귀여울 리가 없어"],
    number: "163",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20120130/3453/17076/medium/6af29873541086aee77439206cb4ef50.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3453/",
    verified: true,
  },
  {
    id: "nendoroid-174",
    name: "넨도로이드 카나메 마도카",
    englishName: "Nendoroid Madoka Kaname",
    aliases: ["카나메 마도카", "마도카", "Madoka Kaname", "마법소녀 마도카 마기카"],
    number: "174",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20110808/3250/14940/medium/5e1e4d3239c7ed69bfbcad189ca00d7d.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3250/",
    verified: true,
  },
  {
    id: "nendoroid-204",
    name: "넨도로이드 멘마",
    englishName: "Nendoroid Menma",
    aliases: ["멘마", "메이코 혼마", "Menma", "Meiko Honma", "아노하나"],
    number: "204",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20120328/3516/17901/medium/8c7d72abcac4033535f4082b64dd517a.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3516/",
    verified: true,
  },
  {
    id: "nendoroid-207",
    name: "넨도로이드 스노우 미쿠 푹신푹신 코트 Ver.",
    englishName: "Nendoroid Snow Miku: Fluffy Coat Ver.",
    aliases: ["스노우 미쿠 푹신푹신 코트", "스노우 미쿠 코트", "Snow Miku Fluffy Coat", "설미쿠"],
    number: "207",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20120116/3438/16906/medium/8192da72a120669851f53050ab879cb3.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3438/",
    verified: true,
  },
  {
    id: "nendoroid-303",
    name: "넨도로이드 스노우 미쿠 딸기 백무구 Ver.",
    englishName: "Nendoroid Snow Miku: Strawberry White Kimono Ver.",
    aliases: ["스노우 미쿠 딸기 백무구", "딸기 백무구", "Strawberry White Kimono", "설미쿠"],
    number: "303",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20120905/3666/20276/medium/93bad2aa646aba958d55a2c052ff74a6.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/3666/",
    verified: true,
  },
  {
    id: "nendoroid-380",
    name: "넨도로이드 스노우 미쿠 매지컬 스노우 Ver.",
    englishName: "Nendoroid Snow Miku: Magical Snow Ver.",
    aliases: ["스노우 미쿠 매지컬 스노우", "매지컬 스노우", "Snow Miku Magical Snow", "설미쿠"],
    number: "380",
    maker: "Good Smile Company",
    release: "구판 · 공식 가품 사례 확인",
    image: "https://images.goodsmile.info/cgm/images/product/20131125/4133/27202/medium/be02d5a554b606a7efe93ee8ba6f759b.jpg",
    officialUrl: "https://partner.goodsmile.info/support/eng/fake/en/4133-1/",
    verified: true,
  },
  {
    id: "nendoroid-40",
    name: "넨도로이드 카가미네 렌",
    englishName: "Nendoroid Kagamine Len",
    aliases: ["카가미네 렌", "렌", "Kagamine Len", "보컬로이드", "Vocaloid"],
    number: "40",
    maker: "Good Smile Company",
    release: "2008.07 · 2013.07 재판",
    image: "https://images.goodsmile.info/cgm/images/product/20091023/263/202/large/23712dd6813bf396e821f2b4a0267ccd.jpg",
    officialUrl: "https://www.goodsmile.info/en/product/263/Nendoroid%2BKagamine%2BLen.html",
    verified: true,
  },
  {
    id: "nendoroid-1151",
    name: "넨도로이드 하츠네 미쿠 매지컬 미라이 2018 Ver.",
    englishName: "Nendoroid Hatsune Miku: Magical Mirai 2018 Ver.",
    aliases: [
      "하츠네 미쿠",
      "미쿠",
      "매지컬 미라이 2018",
      "매지컬미라이 2018",
      "마지미라 2018",
      "Hatsune Miku",
      "Magical Mirai 2018",
      "Character Vocal Series 01",
      "보컬로이드",
      "Vocaloid",
    ],
    number: "1151",
    maker: "Good Smile Company",
    release: "2020.02",
    image: "https://storage.googleapis.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190703/8513/61839/large/c97e3af94173ba2e9decf91ea62400e2.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6221/Nendoroid%2BHatsune%2BMiku%2BMagical%2BMirai%2B2018%2BVer",
    verified: true,
  },
  {
    id: "nendoroid-2069",
    name: "넨도로이드 고토 히토리",
    englishName: "Nendoroid Hitori Gotoh",
    aliases: ["고토 히토리", "히토리", "봇치", "봇치짱", "Hitori Gotoh", "Bocchi", "봇치 더 록", "Bocchi the Rock!"],
    number: "2069",
    maker: "Good Smile Company",
    release: "2023.08 · 2024.06/2025.12 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230201/13918/111100/large/cba8633e99f8ed6a2fa46a01fdc049cc.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11603/Nendoroid%2BHitori%2BGotoh",
    verified: true,
  },
  {
    id: "nendoroid-2242",
    name: "넨도로이드 이지치 니지카",
    englishName: "Nendoroid Nijika Ijichi",
    aliases: ["이지치 니지카", "니지카", "Nijika Ijichi", "봇치 더 록", "Bocchi the Rock!", "결속밴드"],
    number: "2242",
    maker: "Good Smile Company",
    release: "2024.03 · 2025.09 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230915/14964/121018/large/62e1e0534d88536f071cf6ff67b81682.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12649/Nendoroid%2BNijika%2BIjichi",
    verified: true,
  },
  {
    id: "nendoroid-2243",
    name: "넨도로이드 야마다 료",
    englishName: "Nendoroid Ryo Yamada",
    aliases: ["야마다 료", "료", "Ryo Yamada", "봇치 더 록", "Bocchi the Rock!", "결속밴드"],
    number: "2243",
    maker: "Good Smile Company",
    release: "2024.04 · 2025.09 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230927/15036/121739/large/ae3a9d3f8844877cd3688c79d3ef1168.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12720/Nendoroid%2BRyo%2BYamada",
    verified: true,
  },
  {
    id: "nendoroid-2244",
    name: "넨도로이드 키타 이쿠요",
    englishName: "Nendoroid Ikuyo Kita",
    aliases: ["키타 이쿠요", "키타", "Ikuyo Kita", "봇치 더 록", "Bocchi the Rock!", "결속밴드"],
    number: "2244",
    maker: "Good Smile Company",
    release: "2024.02 · 2025.09 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230825/14856/119979/large/dbb8d81b010d0eb328da3922ddfc59cc.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12541/Nendoroid%2BIkuyo%2BKita",
    verified: true,
  },
  {
    id: "nendoroid-2269",
    name: "넨도로이드 히로이 키쿠리",
    englishName: "Nendoroid Kikuri Hiroi",
    aliases: ["히로이 키쿠리", "키쿠리", "Kikuri Hiroi", "봇치 더 록", "Bocchi the Rock!", "SICK HACK"],
    number: "2269",
    maker: "Good Smile Company",
    release: "2024.06 · 2025.09 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20231204/15315/124341/large/ef9ebc0aaffc16be9eea0100307e2cb2.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12998/Nendoroid%2BKikuri%2BHiroi",
    verified: true,
  },
  {
    id: "nendoroid-2307",
    name: "넨도로이드 이지치 세이카",
    englishName: "Nendoroid Seika Ijichi",
    aliases: ["이지치 세이카", "세이카", "Seika Ijichi", "봇치 더 록", "Bocchi the Rock!", "STARRY"],
    number: "2307",
    maker: "Good Smile Company",
    release: "2024.08",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/55193/UKyWJt0eYH98a1QETuj6b3w2NhXFmnp7.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/55193/Nendoroid%2BSeika%2BIjichi",
    verified: true,
  },
  {
    id: "nendoroid-2369",
    name: "넨도로이드 고토 히토리 인정욕구 몬스터 Ver.",
    englishName: "Nendoroid Hitori Gotoh: Attention-Seeking Monster Ver.",
    aliases: ["고토 히토리 인정욕구 몬스터", "승인욕구 몬스터", "관심받고 싶은 괴물", "Hitori Gotoh Attention-Seeking Monster", "봇치", "봇치 더 록", "Bocchi the Rock!"],
    number: "2369",
    maker: "Good Smile Company",
    release: "2024.09",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/56840/czNL0t12HSXiVnv74fWrb5DsxhBmy9kJ.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/56840/Nendoroid%2BHitori%2BGotoh%2BAttention-Seeking%2BMonster%2BVer.",
    verified: true,
  },
  {
    id: "nendoroid-2686",
    name: "넨도로이드 PA씨",
    englishName: "Nendoroid PA-san",
    aliases: ["PA씨", "PA상", "PA-san", "피에이씨", "봇치 더 록", "Bocchi the Rock!", "STARRY"],
    number: "2686",
    maker: "Good Smile Company",
    release: "2025.06",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/60958/4ce50a4730757f8217972da4b41c36e1.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/60958/Nendoroid%2BPA-san",
    verified: true,
  },
  {
    id: "nendoroid-2729",
    name: "넨도로이드 이지치 니지카 사복 Ver.",
    englishName: "Nendoroid Nijika Ijichi: Casual Clothes Ver.",
    aliases: ["이지치 니지카 사복", "니지카 사복", "Nijika Ijichi Casual Clothes", "봇치 더 록", "Bocchi the Rock!", "결속밴드"],
    number: "2729",
    maker: "Good Smile Company",
    release: "2025.07",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1136102/ypmhUN2a6AS5XYj97GQxkVMsdPZ4BnD0.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1136102/Nendoroid%2BNijika%2BIjichi%2BCasual%2BClothes%2BVer.",
    verified: true,
  },
  {
    id: "nendoroid-2737",
    name: "넨도로이드 고토 히토리 메이드 Ver. [Basic]",
    englishName: "Nendoroid Hitori Gotoh: Maid Ver. [Basic]",
    aliases: ["고토 히토리 메이드", "봇치 메이드", "Hitori Gotoh Maid", "Basic", "베이직", "봇치 더 록", "Bocchi the Rock!"],
    number: "2737",
    maker: "Good Smile Company",
    release: "2025.07",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1136103/znPA0B1eXgsFCr2VKpfh6Ytkcm95WUNa.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1136103/Nendoroid%2BHitori%2BGotoh%2BMaid%2BVer.%2BBasic%2B",
    verified: true,
  },
  {
    id: "nendoroid-2762",
    name: "넨도로이드 키타 이쿠요 사복 Ver.",
    englishName: "Nendoroid Ikuyo Kita: Casual Clothes Ver.",
    aliases: ["키타 이쿠요 사복", "키타 사복", "Ikuyo Kita Casual Clothes", "봇치 더 록", "Bocchi the Rock!", "결속밴드"],
    number: "2762",
    maker: "Good Smile Company",
    release: "2025.10",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1137007/8J6EZfrYSP1pFmzhXU35vgMTQVcRWH29.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1137007/Nendoroid%2BIkuyo%2BKita%2BCasual%2BClothes%2BVer.",
    verified: true,
  },
  {
    id: "nendoroid-2785",
    name: "넨도로이드 야마다 료 사복 Ver.",
    englishName: "Nendoroid Ryo Yamada: Casual Clothes Ver.",
    aliases: ["야마다 료 사복", "료 사복", "Ryo Yamada Casual Clothes", "봇치 더 록", "Bocchi the Rock!", "결속밴드"],
    number: "2785",
    maker: "Good Smile Company",
    release: "2025.10",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1136475/vN6jT0hLCesQG85bF19VzJHa4dymBxEg.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1136475/Nendoroid%2BRyo%2BYamada%2BCasual%2BClothes%2BVer.",
    verified: true,
  },
  {
    id: "nendoroid-2821",
    name: "넨도로이드 고토 히토리 운동복 Ver.",
    englishName: "Nendoroid Hitori Gotoh: Tracksuit Ver.",
    aliases: ["고토 히토리 운동복", "봇치 운동복", "봇치 추리닝", "Hitori Gotoh Tracksuit", "봇치 더 록", "Bocchi the Rock!"],
    number: "2821",
    maker: "Good Smile Company",
    release: "2026.01",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1137316/vrQ9gG6RDKHCh5W31N87sqktedazcMfP.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1137316/Nendoroid%2BHitori%2BGotoh%2BTracksuit%2BVer.",
    verified: true,
  },
  {
    id: "nendoroid-682",
    name: "넨도로이드 우즈마키 나루토",
    englishName: "Nendoroid Naruto Uzumaki",
    aliases: ["우즈마키 나루토","Naruto Uzumaki","나루토","Naruto Shippuden","naruto"],
    number: "682",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20160927/5981/41605/large/52b7d31543c162aca4cd08b4a0af2788.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3724",
    verified: true,
  },
  {
    id: "nendoroid-707",
    name: "넨도로이드 우치하 사스케",
    englishName: "Nendoroid Sasuke Uchiha",
    aliases: ["우치하 사스케","Sasuke Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "707",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20161201/6106/42712/large/f528bfe7d67015eabfb2a47788ffb308.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3844",
    verified: true,
  },
  {
    id: "nendoroid-724",
    name: "넨도로이드 하타케 카카시",
    englishName: "Nendoroid Kakashi Hatake",
    aliases: ["하타케 카카시","Kakashi Hatake","나루토","Naruto Shippuden","naruto"],
    number: "724",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20170113/6174/43173/large/b8b7c2377ac1eccd19b779344c17453a.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3912",
    verified: true,
  },
  {
    id: "nendoroid-820",
    name: "넨도로이드 우치하 이타치",
    englishName: "Nendoroid Itachi Uchiha",
    aliases: ["우치하 이타치","Itachi Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "820",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20170905/6710/47433/large/125d2ee25ad3ac94ddb7c33400838f81.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4437",
    verified: true,
  },
  {
    id: "nendoroid-833",
    name: "넨도로이드 하루노 사쿠라",
    englishName: "Nendoroid Sakura Haruno",
    aliases: ["하루노 사쿠라","Sakura Haruno","나루토","Naruto Shippuden","naruto"],
    number: "833",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20171003/6764/47908/large/f40efe8b240e9f158495135a976aa272.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4491",
    verified: true,
  },
  {
    id: "nendoroid-872",
    name: "넨도로이드 우즈마키 나루토 중국 전시회 Ver.",
    englishName: "Nendoroid Naruto Uzumaki: NARUTO Animation Exhibition in China Ver.",
    aliases: ["우즈마키 나루토 중국 전시회 Ver.","Naruto Uzumaki: NARUTO Animation Exhibition in China Ver.","나루토","Naruto Shippuden","naruto"],
    number: "872",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180306/7104/50684/large/3fb759ce66e686f40a861b83ed96787a.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4823",
    verified: true,
  },
  {
    id: "nendoroid-879",
    name: "넨도로이드 휴우가 히나타",
    englishName: "Nendoroid Hinata Hyuga",
    aliases: ["휴우가 히나타","Hinata Hyuga","나루토","Naruto Shippuden","naruto"],
    number: "879",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180123/7004/49780/large/f9920095a8e0e9b08ebf3be4fa6b8476.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4724",
    verified: true,
  },
  {
    id: "nendoroid-886",
    name: "넨도로이드 지라이야 & 가마분타 세트",
    englishName: "Nendoroid Jiraiya & Gamabunta Set",
    aliases: ["지라이야 & 가마분타 세트","Jiraiya & Gamabunta Set","나루토","Naruto Shippuden","naruto"],
    number: "886",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180511/7272/51908/large/3d612be69a5d5a0caa8f4ba108ea10eb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/4988",
    verified: true,
  },
  {
    id: "nendoroid-956",
    name: "넨도로이드 가아라",
    englishName: "Nendoroid Gaara",
    aliases: ["가아라","Gaara","나루토","Naruto Shippuden","naruto"],
    number: "956",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180625/7379/52822/large/cfa518492423633c15305ec0e4da8248.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/5095",
    verified: true,
  },
  {
    id: "nendoroid-991",
    name: "넨도로이드 쿠로사키 이치고",
    englishName: "Nendoroid Ichigo Kurosaki",
    aliases: ["쿠로사키 이치고","Ichigo Kurosaki","블리치","BLEACH","bleach"],
    number: "991",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180831/7581/54256/large/0e28b01c432abbd36b0d1c0b3f966b7c.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/5297",
    verified: true,
  },
  {
    id: "nendoroid-1008",
    name: "넨도로이드 츠나데",
    englishName: "Nendoroid Tsunade",
    aliases: ["츠나데","Tsunade","나루토","Naruto Shippuden","naruto"],
    number: "1008",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20180926/7639/54864/large/a27b71e9f4cbdff73367c4cb008a6a25.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/5355",
    verified: true,
  },
  {
    id: "nendoroid-1181",
    name: "넨도로이드 나라 시카마루",
    englishName: "Nendoroid Shikamaru Nara",
    aliases: ["나라 시카마루","Shikamaru Nara","나루토","Naruto Shippuden","naruto"],
    number: "1181",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190730/8644/62457/large/32e8e19556da68b0e092e9288215e8bb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6351",
    verified: true,
  },
  {
    id: "nendoroid-1193",
    name: "넨도로이드 카마도 탄지로",
    englishName: "Nendoroid Tanjiro Kamado",
    aliases: ["카마도 탄지로","Tanjiro Kamado","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1193",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190809/8675/62911/large/95348670e396509ffc374dadea387268.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6382",
    verified: true,
  },
  {
    id: "nendoroid-1194",
    name: "넨도로이드 카마도 네즈코",
    englishName: "Nendoroid Nezuko Kamado",
    aliases: ["카마도 네즈코","Nezuko Kamado","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1194",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190823/8726/63216/large/3680bc7a33285fd5039443272c4ab396.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6433",
    verified: true,
  },
  {
    id: "nendoroid-1199",
    name: "넨도로이드 히츠가야 토시로",
    englishName: "Nendoroid Toushiro Hitsugaya",
    aliases: ["히츠가야 토시로","Toushiro Hitsugaya","블리치","BLEACH","bleach"],
    number: "1199",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190910/8782/63546/large/e0d91353ed90f2c13dbfb0a8269919e9.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6489",
    verified: true,
  },
  {
    id: "nendoroid-1232",
    name: "넨도로이드 오로치마루",
    englishName: "Nendoroid Orochimaru",
    aliases: ["오로치마루","Orochimaru","나루토","Naruto Shippuden","naruto"],
    number: "1232",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20191031/8949/65218/large/56c06e0c0ffcbbab42a51ac21febd3e5.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6656",
    verified: true,
  },
  {
    id: "nendoroid-1273",
    name: "넨도로이드 우즈마키 나루토 육도선인 Ver.",
    englishName: "Nendoroid Naruto Uzumaki: Sage of the Six Paths Ver.",
    aliases: ["우즈마키 나루토 육도선인 Ver.","Naruto Uzumaki: Sage of the Six Paths Ver.","나루토","Naruto Shippuden","naruto"],
    number: "1273",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20191227/9142/66526/large/5410e7d7066f438fc7615238708c7ec8.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6849",
    verified: true,
  },
  {
    id: "nendoroid-1303",
    name: "넨도로이드 록 리",
    englishName: "Nendoroid Rock Lee",
    aliases: ["록 리","Rock Lee","나루토","Naruto Shippuden","naruto"],
    number: "1303",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200305/9331/68162/large/3b7d9441442b39e769ec20b72692ba42.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7038",
    verified: true,
  },
  {
    id: "nendoroid-1334",
    name: "넨도로이드 아가츠마 젠이츠",
    englishName: "Nendoroid Zenitsu Agatsuma",
    aliases: ["아가츠마 젠이츠","Zenitsu Agatsuma","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1334",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200501/9477/84478/large/14ba78df5b27688cb75fb8ffa9453a75.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7184",
    verified: true,
  },
  {
    id: "nendoroid-1354",
    name: "넨도로이드 휴우가 네지",
    englishName: "Nendoroid Neji Hyuga",
    aliases: ["휴우가 네지","Neji Hyuga","나루토","Naruto Shippuden","naruto"],
    number: "1354",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200521/9535/69930/large/e101de5204248d0b7f2e2366b731b12f.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7238",
    verified: true,
  },
  {
    id: "nendoroid-1361",
    name: "넨도로이드 하시비라 이노스케",
    englishName: "Nendoroid Inosuke Hashibira",
    aliases: ["하시비라 이노스케","Inosuke Hashibira","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1361",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200603/9605/70420/large/2a47b57d772d64e9cc392cdcfccf57c3.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7307",
    verified: true,
  },
  {
    id: "nendoroid-1373",
    name: "넨도로이드 사소리",
    englishName: "Nendoroid Sasori",
    aliases: ["사소리","Sasori","나루토","Naruto Shippuden","naruto"],
    number: "1373",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200609/9624/70668/large/d3ed147f8ec84c6d7e4bad48bb2d00b0.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7326",
    verified: true,
  },
  {
    id: "nendoroid-1408",
    name: "넨도로이드 토미오카 기유",
    englishName: "Nendoroid Giyu Tomioka",
    aliases: ["토미오카 기유","Giyu Tomioka","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1408",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200715/9778/71979/large/cf36f88cfcb8e2934010482322e6785f.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7480",
    verified: true,
  },
  {
    id: "nendoroid-1479",
    name: "넨도로이드 이타도리 유지",
    englishName: "Nendoroid Yuji Itadori",
    aliases: ["이타도리 유지","Yuji Itadori","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1479",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/7867/7617d3ea951443a2decb80f85020d067.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7867",
    verified: true,
  },
  {
    id: "nendoroid-1481",
    name: "넨도로이드 데이다라",
    englishName: "Nendoroid Deidara",
    aliases: ["데이다라","Deidara","나루토","Naruto Shippuden","naruto"],
    number: "1481",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200928/10144/75049/large/613dcccc241b49389098f09ce694a676.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7838",
    verified: true,
  },
  {
    id: "nendoroid-1506",
    name: "넨도로이드 후시구로 메구미",
    englishName: "Nendoroid Megumi Fushiguro",
    aliases: ["후시구로 메구미","Megumi Fushiguro","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1506",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/8107/7b3890ef646fad029de87b5d5bcf9e1e.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8107",
    verified: true,
  },
  {
    id: "nendoroid-1510",
    name: "넨도로이드 카마도 탄지로 최종선별 Ver.",
    englishName: "Nendoroid Tanjiro Kamado: Final Selection Ver.",
    aliases: ["카마도 탄지로 최종선별 Ver.","Tanjiro Kamado: Final Selection Ver.","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1510",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20201021/10258/77749/large/d5b87eb8438c93bf5a11b0f8801de835.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7952",
    verified: true,
  },
  {
    id: "nendoroid-1524",
    name: "넨도로이드 나미카제 미나토",
    englishName: "Nendoroid Minato Namikaze",
    aliases: ["나미카제 미나토","Minato Namikaze","나루토","Naruto Shippuden","naruto"],
    number: "1524",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20201118/10411/78083/large/cb341f9826b56a4a6226f8842a0e7d30.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8105",
    verified: true,
  },
  {
    id: "nendoroid-1528",
    name: "넨도로이드 고죠 사토루",
    englishName: "Nendoroid Satoru Gojo",
    aliases: ["고죠 사토루","Satoru Gojo","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1528",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/8185/xqzEit1jAG7Hu2839cgBhNeT45PLdvKb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8185",
    verified: true,
  },
  {
    id: "nendoroid-1541",
    name: "넨도로이드 렌고쿠 쿄쥬로",
    englishName: "Nendoroid Kyojuro Rengoku",
    aliases: ["렌고쿠 쿄쥬로","Kyojuro Rengoku","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1541",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20201221/10607/79376/large/252a9defd5a7cd4d55e65ee015a27111.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8301",
    verified: true,
  },
  {
    id: "nendoroid-1548",
    name: "넨도로이드 쿠기사키 노바라",
    englishName: "Nendoroid Nobara Kugisaki",
    aliases: ["쿠기사키 노바라","Nobara Kugisaki","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1548",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210106/10648/79537/large/d1505881b0821fb8d9a9a24e129f66ce.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8342",
    verified: true,
  },
  {
    id: "nendoroid-1560",
    name: "넨도로이드 덴지",
    englishName: "Nendoroid Denji",
    aliases: ["덴지","Denji","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "1560",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/8409/0FnUA4QcRW1zxDXLaqSVNPHYETy6r5m7.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8409",
    verified: true,
  },
  {
    id: "nendoroid-1569",
    name: "넨도로이드 사비토",
    englishName: "Nendoroid Sabito",
    aliases: ["사비토","Sabito","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1569",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210209/10789/81137/large/db427aa438e8915a685ac6d5f8eb99b8.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8483",
    verified: true,
  },
  {
    id: "nendoroid-1570",
    name: "넨도로이드 마코모",
    englishName: "Nendoroid Makomo",
    aliases: ["마코모","Makomo","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1570",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210209/10790/81169/large/1f150eb9bd62674d67d4d6d0cd85c984.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8484",
    verified: true,
  },
  {
    id: "nendoroid-1580",
    name: "넨도로이드 파워",
    englishName: "Nendoroid Power",
    aliases: ["파워","Power","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "1580",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210219/10834/81352/large/f85662773a3004d8c1397adb1d6d3507.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8528",
    verified: true,
  },
  {
    id: "nendoroid-1636",
    name: "넨도로이드 하타케 카카시 암부 Ver.",
    englishName: "Nendoroid Kakashi Hatake: Anbu Black Ops Ver.",
    aliases: ["하타케 카카시 암부 Ver.","Kakashi Hatake: Anbu Black Ops Ver.","나루토","Naruto Shippuden","naruto"],
    number: "1636",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210614/11348/86493/large/d999a1ac81939067d01ecf2a3cf5c1db.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9042",
    verified: true,
  },
  {
    id: "nendoroid-1655",
    name: "넨도로이드 코쵸우 시노부",
    englishName: "Nendoroid Shinobu Kocho",
    aliases: ["코쵸우 시노부","Shinobu Kocho","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1655",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210705/11453/86903/large/54ff64a0dcbe36d5a9e9bbff790dab3f.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9147",
    verified: true,
  },
  {
    id: "nendoroid-1726",
    name: "넨도로이드 우치하 이타치 암부 Ver.",
    englishName: "Nendoroid Itachi Uchiha: Anbu Black Ops Ver.",
    aliases: ["우치하 이타치 암부 Ver.","Itachi Uchiha: Anbu Black Ops Ver.","나루토","Naruto Shippuden","naruto"],
    number: "1726",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20211002/11851/91232/large/d1c4ad3371ae2e2f15f7ba79ae8fc950.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9540",
    verified: true,
  },
  {
    id: "nendoroid-1750",
    name: "넨도로이드 이누마키 토게",
    englishName: "Nendoroid Toge Inumaki",
    aliases: ["이누마키 토게","Toge Inumaki","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1750",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/9667/048e36562a362bb27bf002721a9dbce4.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9667",
    verified: true,
  },
  {
    id: "nendoroid-1766",
    name: "넨도로이드 옷코츠 유타 주술회전 0 Ver.",
    englishName: "Nendoroid Yuta Okkotsu: Jujutsu Kaisen 0 Ver.",
    aliases: ["옷코츠 유타 주술회전 0 Ver.","Yuta Okkotsu: Jujutsu Kaisen 0 Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1766",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20211124/12044/92446/large/553f382dc1ac69f6077c28810c5dd680.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9732",
    verified: true,
  },
  {
    id: "nendoroid-1767",
    name: "넨도로이드 고죠 사토루 주술회전 0 Ver.",
    englishName: "Nendoroid Satoru Gojo: Jujutsu Kaisen 0 Ver.",
    aliases: ["고죠 사토루 주술회전 0 Ver.","Satoru Gojo: Jujutsu Kaisen 0 Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1767",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20211124/12045/95226/large/70b5015f1120eb1df463685c6074d4a1.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9733",
    verified: true,
  },
  {
    id: "nendoroid-1768",
    name: "넨도로이드 게토 스구루 주술회전 0 Ver.",
    englishName: "Nendoroid Suguru Geto: Jujutsu Kaisen 0 Ver.",
    aliases: ["게토 스구루 주술회전 0 Ver.","Suguru Geto: Jujutsu Kaisen 0 Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1768",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20211124/12046/95166/large/c6d6c3ad5271df5fafa74acc3ea42bb1.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9734",
    verified: true,
  },
  {
    id: "nendoroid-1812",
    name: "넨도로이드 나나미 켄토",
    englishName: "Nendoroid Kento Nanami",
    aliases: ["나나미 켄토","Kento Nanami","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1812",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20220128/12289/94869/large/1f5d9e4f02d1059ce65869b6cb95abaf.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9977",
    verified: true,
  },
  {
    id: "nendoroid-1830",
    name: "넨도로이드 우즈이 텐겐",
    englishName: "Nendoroid Tengen Uzui",
    aliases: ["우즈이 텐겐","Tengen Uzui","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1830",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20220218/12366/95610/large/aa7426ba3477ed4cf1e81ab74c382a12.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/10054",
    verified: true,
  },
  {
    id: "nendoroid-1834",
    name: "넨도로이드 료멘 스쿠나",
    englishName: "Nendoroid Sukuna",
    aliases: ["료멘 스쿠나","Sukuna","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "1834",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/10133/54b47cdea45592f2ed4e8e946ae5cb49.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/10133",
    verified: true,
  },
  {
    id: "nendoroid-1948",
    name: "넨도로이드 카마도 네즈코 각성 Ver.",
    englishName: "Nendoroid Nezuko Kamado (Demon Form Advancing Ver.)",
    aliases: ["카마도 네즈코 각성 Ver.","Nezuko Kamado (Demon Form Advancing Ver.)","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "1948",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20220803/13073/104056/large/93ec09a2ed01bb7c29f834755a292950.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/10758",
    verified: true,
  },
  {
    id: "nendoroid-2003",
    name: "넨도로이드 하야카와 아키",
    englishName: "Nendoroid Aki Hayakawa",
    aliases: ["하야카와 아키","Aki Hayakawa","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "2003",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20221124/13591/107704/large/3ddad1fb92e197d92fae77d79d25aca0.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11276",
    verified: true,
  },
  {
    id: "nendoroid-2004",
    name: "넨도로이드 마키마",
    englishName: "Nendoroid Makima",
    aliases: ["마키마","Makima","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "2004",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20221124/13590/107696/large/e3eb1d64c721a98a7ce0ceba701fb209.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11275",
    verified: true,
  },
  {
    id: "nendoroid-2014",
    name: "넨도로이드 히가시야마 코베니",
    englishName: "Nendoroid Kobeni",
    aliases: ["히가시야마 코베니","Kobeni","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "2014",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/11308/d0c5pNWiY3C4QPnzLUyJhfEZ9x7eXMVk.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11308",
    verified: true,
  },
  {
    id: "nendoroid-2092",
    name: "넨도로이드 렌고쿠 센쥬로",
    englishName: "Nendoroid Senjuro Rengoku",
    aliases: ["렌고쿠 센쥬로","Senjuro Rengoku","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2092",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230313/14105/112836/large/23d249a8c56c8c99109a18a272896eaa.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11790",
    verified: true,
  },
  {
    id: "nendoroid-2112",
    name: "넨도로이드 아카자",
    englishName: "Nendoroid Akaza",
    aliases: ["아카자","Akaza","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2112",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230420/14296/114581/large/d6e5d7b661e861bf9da059e434b83bb4.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11981",
    verified: true,
  },
  {
    id: "nendoroid-2120",
    name: "넨도로이드 우치하 오비토",
    englishName: "Nendoroid Obito Uchiha",
    aliases: ["우치하 오비토","Obito Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "2120",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230612/14479/119394/large/16e3716df40f953e905034fddedfcfcf.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12164",
    verified: true,
  },
  {
    id: "nendoroid-2175",
    name: "넨도로이드 우치하 마다라",
    englishName: "Nendoroid Madara Uchiha",
    aliases: ["우치하 마다라","Madara Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "2175",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230511/14367/115236/large/36efb9ab8495e8357fb8f60930c65aeb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12052",
    verified: true,
  },
  {
    id: "nendoroid-2205",
    name: "넨도로이드 고죠 사토루 고등전문학교 Ver.",
    englishName: "Nendoroid Satoru Gojo: Tokyo Jujutsu High School Ver.",
    aliases: ["고죠 사토루 고등전문학교 Ver.","Satoru Gojo: Tokyo Jujutsu High School Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2205",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/12289/449e249d91b186e9841499ee5d07849c.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12289",
    verified: true,
  },
  {
    id: "nendoroid-2206",
    name: "넨도로이드 게토 스구루 고등전문학교 Ver.",
    englishName: "Nendoroid Suguru Geto: Tokyo Jujutsu High School Ver.",
    aliases: ["게토 스구루 고등전문학교 Ver.","Suguru Geto: Tokyo Jujutsu High School Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2206",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/12290/9a598dd473339b0e6a808bc6486a33ce.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12290",
    verified: true,
  },
  {
    id: "nendoroid-2217",
    name: "넨도로이드 칸로지 미츠리",
    englishName: "Nendoroid Mitsuri Kanroji",
    aliases: ["칸로지 미츠리","Mitsuri Kanroji","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2217",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230829/14890/120353/large/3b1fb0d4ef318a7784b92c7346838087.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12575",
    verified: true,
  },
  {
    id: "nendoroid-2218",
    name: "넨도로이드 토키토 무이치로",
    englishName: "Nendoroid Muichiro Tokito",
    aliases: ["토키토 무이치로","Muichiro Tokito","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2218",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230720/14689/118454/large/08c7397abd7fab662ff8b13b84e95711.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12374",
    verified: true,
  },
  {
    id: "nendoroid-2280",
    name: "넨도로이드 후시구로 토우지",
    englishName: "Nendoroid Toji Fushiguro",
    aliases: ["후시구로 토우지","Toji Fushiguro","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2280",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230927/15038/121755/large/2fa918d4a11397ee4ad2ebde13512a85.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12722",
    verified: true,
  },
  {
    id: "nendoroid-2290",
    name: "넨도로이드 쵸소우",
    englishName: "Nendoroid Choso",
    aliases: ["쵸소우","Choso","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2290",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/12832/ded498960587d15c502c42d3163c5886.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12832",
    verified: true,
  },
  {
    id: "nendoroid-2305",
    name: "넨도로이드 이에이리 쇼코 고등전문학교 Ver.",
    englishName: "Nendoroid Shoko Ieiri: Tokyo Jujutsu High School Ver.",
    aliases: ["이에이리 쇼코 고등전문학교 Ver.","Shoko Ieiri: Tokyo Jujutsu High School Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2305",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20231023/15112/122473/large/d3f4b3a7bad52c1abf8a52ed689b5fbb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12795",
    verified: true,
  },
  {
    id: "nendoroid-2436",
    name: "넨도로이드 우치하 시스이",
    englishName: "Nendoroid Shisui Uchiha",
    aliases: ["우치하 시스이","Shisui Uchiha","나루토","Naruto Shippuden","naruto"],
    number: "2436",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/56499/xj81nygZwtRFrh5TN7943BHk6PVvupUM.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/56499",
    verified: true,
  },
  {
    id: "nendoroid-2440",
    name: "넨도로이드 고죠 사토루 정장 Ver.",
    englishName: "Nendoroid Satoru Gojo: Suit Ver.",
    aliases: ["고죠 사토루 정장 Ver.","Satoru Gojo: Suit Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2440",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/36214/gFVKNXMJfTAPeE289cnyaWRk3Y5qsBGS.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/36214",
    verified: true,
  },
  {
    id: "nendoroid-2441",
    name: "넨도로이드 게토 스구루 정장 Ver.",
    englishName: "Nendoroid Suguru Geto: Suit Ver.",
    aliases: ["게토 스구루 정장 Ver.","Suguru Geto: Suit Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2441",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/36215/vZ2SMAxwiQGBusVqc9mrKnPNWRzUHeX7.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/36215",
    verified: true,
  },
  {
    id: "nendoroid-2505",
    name: "넨도로이드 시나즈가와 겐야",
    englishName: "Nendoroid Genya Shinazugawa",
    aliases: ["시나즈가와 겐야","Genya Shinazugawa","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2505",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/34679/TripG7eHyP1jsUZNkm9Bt2nzbFguhRCQ.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/34679",
    verified: true,
  },
  {
    id: "nendoroid-2506",
    name: "넨도로이드 시나즈가와 사네미",
    englishName: "Nendoroid Sanemi Shinazugawa",
    aliases: ["시나즈가와 사네미","Sanemi Shinazugawa","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "2506",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/35752/tD65FWEyzY0jniwTvbMmR4HPBUVL9Zh3.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/35752",
    verified: true,
  },
  {
    id: "nendoroid-2687",
    name: "넨도로이드 센쥬 하시라마",
    englishName: "Nendoroid Hashirama Senju",
    aliases: ["센쥬 하시라마","Hashirama Senju","나루토","Naruto Shippuden","naruto"],
    number: "2687",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/57420/9WhJEdjM82wzQ0LZx5eVukvCTmYt6a1c.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/57420",
    verified: true,
  },
  {
    id: "nendoroid-2865",
    name: "넨도로이드 레제",
    englishName: "Nendoroid Reze",
    aliases: ["레제","Reze","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "2865",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/62079/ZjBXGDJn7EgepLhRiaPCsSHf2rF6k8Ky.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/62079",
    verified: true,
  },
  {
    id: "nendoroid-2933",
    name: "넨도로이드 옷코츠 유타 사형 집행 Ver.",
    englishName: "Nendoroid Yuta Okkotsu: Execution Ver.",
    aliases: ["옷코츠 유타 사형 집행 Ver.","Yuta Okkotsu: Execution Ver.","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2933",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1139229/0A1yYgJLqk4HFS75u6C2EZTswjzpRWmf.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1139229",
    verified: true,
  },
  {
    id: "nendoroid-2977",
    name: "넨도로이드 이타도리 유지 사형 집행 Ver. 베이직",
    englishName: "Nendoroid Yuji Itadori: Execution Ver. [Basic]",
    aliases: ["이타도리 유지 사형 집행 Ver. 베이직","Yuji Itadori: Execution Ver. [Basic]","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "2977",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1140616/tuEc07NGJB2LRTH9ek6gjmWCsPzKwFpZ.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1140616",
    verified: true,
  },
  {
    id: "nendoroid-3034",
    name: "넨도로이드 도우마",
    englishName: "Nendoroid Doma",
    aliases: ["도우마","Doma","귀멸의 칼날","Demon Slayer: Kimetsu no Yaiba","demon-slayer"],
    number: "3034",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1140601/3EqZA5kvNKHLCp180cBSPgws7XjMezhi.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1140601",
    verified: true,
  },
  {
    id: "nendoroid-3035",
    name: "넨도로이드 젠인 마키 사형 집행 Ver. 베이직",
    englishName: "Nendoroid Maki Zen'in: Execution Ver. [Basic]",
    aliases: ["젠인 마키 사형 집행 Ver. 베이직","Maki Zen'in: Execution Ver. [Basic]","주술회전","Jujutsu Kaisen","jujutsu-kaisen"],
    number: "3035",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1140617/4E2pQes8MUJBmW9YbcAS7gFPXNh6CfHG.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1140617",
    verified: true,
  },
  {
    id: "nendoroid-3041",
    name: "넨도로이드 레제 캐주얼 의상 Ver. 베이직",
    englishName: "Nendoroid Reze: Casual Outfit Ver. [Basic]",
    aliases: ["레제 캐주얼 의상 Ver. 베이직","Reze: Casual Outfit Ver. [Basic]","체인소맨","Chainsaw Man","chainsaw-man"],
    number: "3041",
    maker: "Good Smile Company",
    release: "발매 정보 공식 페이지 확인",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/1141481/QD7mJqbSWKL8i6a5C39cX4ztH0TGpnEZ.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/1141481",
    verified: true,
  },
  {
    id: "nendoroid-686",
    name: "넨도로이드 미도리야 이즈쿠 히어로즈 에디션",
    englishName: "Nendoroid Izuku Midoriya: Hero's Edition",
    aliases: ["미도리야 이즈쿠", "데쿠", "Izuku Midoriya", "Deku", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "686",
    maker: "Good Smile Company",
    release: "2017.04 · 2019.01/2019.10 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20161004/5994/41801/large/b6ebd041fc2031586d5402970e8246aa.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3737",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-705",
    name: "넨도로이드 바쿠고 카츠키 히어로즈 에디션",
    englishName: "Nendoroid Katsuki Bakugo: Hero's Edition",
    aliases: ["바쿠고 카츠키", "바쿠고", "Katsuki Bakugo", "Bakugo", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "705",
    maker: "Good Smile Company",
    release: "2017.06 · 2019.01/2019.10 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20161202/6107/42613/large/15187a4c135351d178a378b859e8f365.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/3845",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1112",
    name: "넨도로이드 토도로키 쇼토 히어로즈 에디션",
    englishName: "Nendoroid Shoto Todoroki: Hero's Edition",
    aliases: ["토도로키 쇼토", "토도로키", "Shoto Todoroki", "Todoroki", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1112",
    maker: "Good Smile Company",
    release: "2019.10 · 2022.12 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190319/8187/59019/large/91e06d8df700de60926dd1814feb8ccb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/5895",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1157",
    name: "넨도로이드 우라라카 오챠코 히어로즈 에디션",
    englishName: "Nendoroid Ochaco Uraraka: Hero's Edition",
    aliases: ["우라라카 오챠코", "오챠코", "Ochaco Uraraka", "Uraraka", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1157",
    maker: "Good Smile Company",
    release: "2019.12",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190612/8420/60942/large/69b1502c574333d4ce7cb34445e3f69a.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6128",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1163",
    name: "넨도로이드 토무라 시가라키 빌런즈 에디션",
    englishName: "Nendoroid Tomura Shigaraki: Villain's Edition",
    aliases: ["토무라 시가라키", "시가라키", "Tomura Shigaraki", "Shigaraki", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1163",
    maker: "Good Smile Company",
    release: "2020.01 · 2022.12 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20190627/8475/61366/large/158db7a0648dd592cb7d141f49fd8f8e.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6183",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1234",
    name: "넨도로이드 올마이트",
    englishName: "Nendoroid All Might",
    aliases: ["올마이트", "All Might", "야기 토시노리", "Toshinori Yagi", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1234",
    maker: "Good Smile Company",
    release: "2020.05",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20191112/8972/65112/large/c09fef7da6dc5424500bf43497a80e56.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6679",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1272",
    name: "넨도로이드 아스이 츠유",
    englishName: "Nendoroid Tsuyu Asui",
    aliases: ["아스이 츠유", "츠유", "Tsuyu Asui", "Froppy", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1272",
    maker: "Good Smile Company",
    release: "2020.08",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20191125/9014/66730/large/f3c1612c23cbf4532728f74766bffc6d.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/6721",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1313",
    name: "넨도로이드 키리시마 에이지로",
    englishName: "Nendoroid Eijiro Kirishima",
    aliases: ["키리시마 에이지로", "키리시마", "Eijiro Kirishima", "Kirishima", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1313",
    maker: "Good Smile Company",
    release: "2020.10",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200311/9346/68254/large/41e05e3caf3d6aaca9654299afe38e98.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7053",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1332",
    name: "넨도로이드 미도리야 이즈쿠 코스튬 γ",
    englishName: "Nendoroid Izuku Midoriya: Costume γ",
    aliases: ["미도리야 이즈쿠 코스튬 감마", "데쿠 감마", "Izuku Midoriya Costume Gamma", "Deku", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1332",
    maker: "Good Smile Company",
    release: "2020.12",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200625/9691/71296/large/d8d400004028caac2c7176db9df0b11f.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7393",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1333",
    name: "넨도로이드 토가 히미코",
    englishName: "Nendoroid Himiko Toga",
    aliases: ["토가 히미코", "토가", "Himiko Toga", "Toga", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1333",
    maker: "Good Smile Company",
    release: "2020.11 · 2021.10/2023.08 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200427/9459/69263/large/c521f483cf63d952e979b7b37ebf0dbd.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7166",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1428",
    name: "넨도로이드 이이다 텐야",
    englishName: "Nendoroid Tenya Iida",
    aliases: ["이이다 텐야", "이이다", "Tenya Iida", "Ingenium", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1428",
    maker: "Good Smile Company",
    release: "2021.02",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200720/9800/72595/large/1613d5a1e949a3e03b82abdcc625faac.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7502",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1430",
    name: "넨도로이드 다비",
    englishName: "Nendoroid Dabi",
    aliases: ["다비", "Dabi", "토도로키 토야", "Toya Todoroki", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1430",
    maker: "Good Smile Company",
    release: "2021.03 · 2022.12 재판",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20200803/9893/72873/large/801673d0ce36c9fcab3cbb71fd8bcc97.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/7589",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1595",
    name: "넨도로이드 바쿠고 카츠키 윈터 코스튬 Ver.",
    englishName: "Nendoroid Katsuki Bakugo: Winter Costume Ver.",
    aliases: ["바쿠고 윈터 코스튬", "Katsuki Bakugo Winter Costume", "Bakugo", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "1595",
    maker: "Good Smile Company",
    release: "2021.11",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210322/10950/82749/large/01fbc69a08f43658044f8cb71c812cfb.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/8644",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1691",
    name: "넨도로이드 미도리야 이즈쿠 스텔스 슈트 Ver.",
    englishName: "Nendoroid Izuku Midoriya: Stealth Suit Ver.",
    aliases: ["미도리야 스텔스 슈트", "Izuku Midoriya Stealth Suit", "Deku", "월드 히어로즈 미션", "히로아카", "My Hero Academia"],
    number: "1691",
    maker: "Good Smile Company",
    release: "2022.02",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210802/11596/88137/large/87100c745c73abe65e758ef174b17a08.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9285",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1692",
    name: "넨도로이드 바쿠고 카츠키 스텔스 슈트 Ver.",
    englishName: "Nendoroid Katsuki Bakugo: Stealth Suit Ver.",
    aliases: ["바쿠고 스텔스 슈트", "Katsuki Bakugo Stealth Suit", "Bakugo", "월드 히어로즈 미션", "히로아카", "My Hero Academia"],
    number: "1692",
    maker: "Good Smile Company",
    release: "2022.02",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210802/11598/88163/large/5958ac507447c1f19bffe1ad4b9dfec1.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9287",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1693",
    name: "넨도로이드 토도로키 쇼토 스텔스 슈트 Ver.",
    englishName: "Nendoroid Shoto Todoroki: Stealth Suit Ver.",
    aliases: ["토도로키 스텔스 슈트", "Shoto Todoroki Stealth Suit", "Todoroki", "월드 히어로즈 미션", "히로아카", "My Hero Academia"],
    number: "1693",
    maker: "Good Smile Company",
    release: "2022.02",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20210802/11597/88152/large/e2eb375315e1023bc31de36a5dbc38e7.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/9286",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-1942",
    name: "넨도로이드 로디 소울",
    englishName: "Nendoroid Rody Soul",
    aliases: ["로디 소울", "Rody Soul", "피노", "Pino", "월드 히어로즈 미션", "히로아카", "My Hero Academia"],
    number: "1942",
    maker: "Good Smile Company",
    release: "2023.02",
    image: "https://images.goodsmile.info/cgm/images/product/20220809/13092/102659/medium/5787f871b2bc94b01054bb3cc3a7d8d5.jpg",
    officialUrl: "https://www.goodsmile.info/en/product/13092/",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2065",
    name: "넨도로이드 호크스",
    englishName: "Nendoroid Hawks",
    aliases: ["호크스", "Hawks", "타카미 케이고", "Keigo Takami", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "2065",
    maker: "Good Smile Company",
    release: "2023.09",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230209/13951/111412/large/beb7920d395ef52e548b1f886cce6dea.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/11636",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2312",
    name: "넨도로이드 미도리야 이즈쿠 유에이 교복 Ver.",
    englishName: "Nendoroid Izuku Midoriya: U.A. School Uniform Ver.",
    aliases: ["미도리야 교복", "데쿠 교복", "Izuku Midoriya U.A. School Uniform", "Deku", "히로아카", "My Hero Academia"],
    number: "2312",
    maker: "Good Smile Company",
    release: "2024.05",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20231026/15136/122687/large/09196c05ba786fa19c904e696255d113.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12819",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2313",
    name: "넨도로이드 바쿠고 카츠키 유에이 교복 Ver.",
    englishName: "Nendoroid Katsuki Bakugo: U.A. School Uniform Ver.",
    aliases: ["바쿠고 교복", "Katsuki Bakugo U.A. School Uniform", "Bakugo", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "2313",
    maker: "Good Smile Company",
    release: "2024.05",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20231026/15137/122694/large/37649d3ca6208eec6f65d05818e3ebc8.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/12820",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2342",
    name: "넨도로이드 엔데버",
    englishName: "Nendoroid Endeavor",
    aliases: ["엔데버", "Endeavor", "토도로키 엔지", "Enji Todoroki", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "2342",
    maker: "Good Smile Company",
    release: "2024.07",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/55075/Z3TNufG8a9xcBUArj6HqvDJwmFi2t0np.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/55075",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2401",
    name: "넨도로이드 아이자와 쇼타",
    englishName: "Nendoroid Shota Aizawa",
    aliases: ["아이자와 쇼타", "아이자와", "Shota Aizawa", "Eraser Head", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "2401",
    maker: "Good Smile Company",
    release: "2024.09",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/55717/Yr4n6BazufkpqNKAecHQJLxgGjw95RTM.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/55717",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2402",
    name: "넨도로이드 레이디 나강",
    englishName: "Nendoroid Lady Nagant",
    aliases: ["레이디 나강", "Lady Nagant", "츠츠미 카이나", "Kaina Tsutsumi", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "2402",
    maker: "Good Smile Company",
    release: "2024.09",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/55732/UhMi53HjTrgcw0SKCBFeYDnqPGm67Vt8.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/55732",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2558",
    name: "넨도로이드 카미나리 덴키",
    englishName: "Nendoroid Denki Kaminari",
    aliases: ["카미나리 덴키", "카미나리", "Denki Kaminari", "Chargebolt", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "2558",
    maker: "Good Smile Company",
    release: "2025.02",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/60280/CyrWp94nzDKTRbUALmqjh3HPMQsi6Ze7.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/60280",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2562",
    name: "넨도로이드 미도리야 이즈쿠 결전 코스튬 Ver.",
    englishName: "Nendoroid Izuku Midoriya: Jukketsu Costume Ver.",
    aliases: ["미도리야 결전 코스튬", "Izuku Midoriya Jukketsu Costume", "Deku", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "2562",
    maker: "Good Smile Company",
    release: "2025.02",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/60282/A4ieLs5wQrVmWzyFg1XHRKMEnC3k6Jbq.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/60282",
    verified: true,
    series: "my-hero-academia",
  },
  {
    id: "nendoroid-2563",
    name: "넨도로이드 바쿠고 카츠키 결전 코스튬 Ver.",
    englishName: "Nendoroid Katsuki Bakugo: Jukketsu Costume Ver.",
    aliases: ["바쿠고 결전 코스튬", "Katsuki Bakugo Jukketsu Costume", "Bakugo", "히로아카", "나의 히어로 아카데미아", "My Hero Academia"],
    number: "2563",
    maker: "Good Smile Company",
    release: "2025.02",
    image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/60283/kneXwNS4WqVQPLY1ar25uCBtJUypcAzH.jpg",
    officialUrl: "https://www.goodsmile.com/en/product/60283",
    verified: true,
    series: "my-hero-academia",
  }
];
