import type { CounterfeitCase } from "./counterfeit-cases";

const checkedAt = "2026-07-16";
const communityDefaults = {
  sourceType: "community" as const,
  checkedAt,
  rightsStatus: "unknown_link_only",
  requiresHumanReview: true,
  verdictImpact: "none" as const,
};

export const researchedCommunityCases: CounterfeitCase[] = [
  {
    id: "community-kakashi-724-side-by-side",
    productId: "nendoroid-724",
    title: "패키지와 본체 정품·가품 비교",
    summary: "일본 피규어 전문 판매업체가 No.724의 정품과 가품을 같은 글에서 패키지와 본체 사진으로 나누어 비교했습니다.",
    images: [
      "https://assets.st-note.com/production/uploads/images/64850261/picture_pc_dda3699ae6005c8df07562caaee7fa7f.jpg?width=1200",
      "https://assets.st-note.com/production/uploads/images/64850269/picture_pc_d4c91212afeb76e45b67ad4193de2883.jpg?width=1200",
      "https://assets.st-note.com/production/uploads/images/64850305/picture_pc_2c94dda4e527c03f1e6c24cad40489a1.jpg?width=1200",
      "https://assets.st-note.com/production/uploads/images/64850341/picture_pc_a93248086281dfbc736cb856f9442c75.jpg?width=1200",
    ],
    signals: [
      { evidenceKey: "boxFront", label: "정품·가품 패키지 인쇄와 구성을 나란히 비교" },
      { evidenceKey: "figureFull", label: "본체 외형과 도색 상태를 나란히 비교" },
      { evidenceKey: "parts", label: "얼굴·머리·부속품 구성을 사진으로 비교" },
    ],
    sourceName: "TOYS KING 비교 자료",
    sourceUrl: "https://note.com/yuusukeblog/n/n8ad8d643c0e9",
    sourcePublishedAt: "2021-11-03",
    caseKind: "comparison",
    confidenceLevel: "high",
    verificationStatus: "side_by_side_author_asserted",
    evidenceSummary: "전문 판매업체가 제품 번호와 제조사를 명시하고 패키지·본체 비교 사진을 게시했습니다.",
    ...communityDefaults,
  },
  {
    id: "community-tanjiro-1193-bootleg-box",
    productId: "nendoroid-1193",
    title: "작품 로고가 빠진 No.1193 패키지",
    summary: "구매자가 eBay에서 받은 제품을 가품으로 신고한 게시물입니다. 사진에서 No.1193 박스가 확인되고, 전면 왼쪽 위 작품 로고 누락이 지적됐습니다.",
    images: [
      "https://preview.redd.it/jmsynvlqw97b1.jpg?width=1080&crop=smart&auto=webp&s=1423caa269ddf468272f7bbf69e4a0950bf0ffa5",
      "https://preview.redd.it/9ts2pfoqw97b1.jpg?width=1080&crop=smart&auto=webp&s=695ef5974ae90536314b2e48c50c51c60ec381a7",
    ],
    signals: [
      { evidenceKey: "boxFront", label: "박스 전면에서 No.1193이 확인됨" },
      { evidenceKey: "boxFront", label: "전면 왼쪽 위 작품 로고가 없음" },
    ],
    sourceName: "Reddit 실물 게시물",
    sourceUrl: "https://www.reddit.com/r/Nendoroid/comments/14etezk/just_got_my_first_bootleg_figure_from_ebay_kinda/",
    sourcePublishedAt: "2023-06-21",
    caseKind: "specimen",
    confidenceLevel: "high",
    verificationStatus: "author_asserted",
    evidenceSummary: "작성자가 가품 수령 사실을 명시했고 제품 번호와 패키지 사진이 남아 있습니다.",
    ...communityDefaults,
  },
  {
    id: "community-nezuko-1194-bootleg-specimen",
    productId: "nendoroid-1194",
    title: "대나무 파츠와 비율이 다른 가품 실물",
    summary: "작성자가 Amazon에서 받은 No.1194를 가품이라고 명시한 실물 사진입니다. 관련 토론에서는 대나무 파츠 결합, 본체 크기와 이마 비율, 끈적한 재질감이 지적됐습니다.",
    images: [
      "https://preview.redd.it/53y5e0shf0q61.jpg?width=1080&crop=smart&auto=webp&s=72c35ab32f8386462d3cc91d0b391c94e4d5a454",
      "https://preview.redd.it/csalb0shf0q61.jpg?width=1080&crop=smart&auto=webp&s=97637831bdca7d8d1931f27047f2dd7cddaf8d6e",
    ],
    signals: [
      { evidenceKey: "parts", label: "대나무 파츠가 얼굴에 자연스럽게 맞지 않음" },
      { evidenceKey: "figureFull", label: "본체 크기와 얼굴·이마 비율이 다르게 보임" },
      { evidenceKey: "parts", label: "재질이 저렴하고 끈적하며 결합이 어렵다는 작성자 설명" },
    ],
    sourceName: "Reddit 가품 실물 게시물",
    sourceUrl: "https://www.reddit.com/r/Nendoroid/comments/mfvzk4/my_fake_amazon_nezuko_nendoroid_came_in_the_mail/",
    sourcePublishedAt: "2021-03-29",
    caseKind: "specimen",
    confidenceLevel: "high",
    verificationStatus: "author_asserted",
    evidenceSummary: "가품이라고 명시된 동일 모델 실물 사진과 별도 토론의 제품 특징 설명을 함께 확인했습니다.",
    secondarySources: [
      {
        name: "관련 특징 언급",
        url: "https://www.reddit.com/r/Nendoroid/comments/n4k6bt/bootleg_vs_official_todoroki_so_glad_i_was_able/",
      },
    ],
    ...communityDefaults,
  },
  {
    id: "community-denji-1560-side-by-side",
    productId: "nendoroid-1560",
    title: "본체 크기·눈·머리카락과 포치타 마감 차이",
    summary: "작성자가 기존 가품을 정품으로 교체한 뒤 두 No.1560을 나란히 촬영했습니다. 눈 표현과 머리카락 몰드 잔여물, 본체와 포치타 마감 차이가 언급됐습니다.",
    images: [
      "https://preview.redd.it/8yz93w4qbw9c1.jpg?width=1080&crop=smart&auto=webp&s=d71a62e2983c6088201f8e68dab4ea4f9bb26903",
      "https://preview.redd.it/n29uqvaqbw9c1.jpg?width=1080&crop=smart&auto=webp&s=4e28f3c98d91013edc2d93d1a9effff802427cbf",
      "https://preview.redd.it/zta80dgqbw9c1.jpg?width=1080&crop=smart&auto=webp&s=4f97286a4348a56bae9204bda21f8a7f8330ce6f",
      "https://preview.redd.it/601xdanqbw9c1.jpg?width=1080&crop=smart&auto=webp&s=1b9d883d74ae46a5ae1f1269e7196f17cb39db3d",
    ],
    signals: [
      { evidenceKey: "figureFull", label: "두 본체의 전체 크기와 비율 차이" },
      { evidenceKey: "facePaint", label: "눈 인쇄와 표정의 선명도 차이" },
      { evidenceKey: "facePaint", label: "머리카락에 몰드 잔여물이 보임" },
      { evidenceKey: "parts", label: "포치타 도색·조형과 손잡이 결합 마감 차이" },
    ],
    sourceName: "Reddit 정품·가품 비교",
    sourceUrl: "https://www.reddit.com/r/Nendoroid/comments/18w75br/spot_the_difference/",
    sourcePublishedAt: "2024-01-01",
    caseKind: "comparison",
    confidenceLevel: "high",
    verificationStatus: "side_by_side_author_asserted",
    evidenceSummary: "작성자가 가품을 정품으로 교체했다고 밝히고 동일 모델을 나란히 비교했습니다.",
    ...communityDefaults,
  },
  {
    id: "community-zenitsu-1334-video",
    productId: "nendoroid-1334",
    title: "No.1334 가품 리뷰 영상",
    summary: "영상 제목에 제품 번호와 캐릭터명, 가품 리뷰임을 함께 명시하고 패키지와 본체를 보여주는 사례입니다.",
    images: ["https://i.ytimg.com/vi/-5UHg4BIzag/hqdefault.jpg"],
    signals: [
      { evidenceKey: "boxFront", label: "영상에서 No.1334 패키지를 확인" },
      { evidenceKey: "figureFull", label: "가품으로 소개된 본체와 구성품을 확인" },
    ],
    sourceName: "YouTube 가품 리뷰",
    sourceUrl: "https://www.youtube.com/watch?v=-5UHg4BIzag",
    sourcePublishedAt: null,
    caseKind: "specimen",
    confidenceLevel: "medium",
    verificationStatus: "author_asserted_video",
    evidenceSummary: "영상 작성자가 No.1334 가품 리뷰임을 명시했습니다.",
    ...communityDefaults,
  },
  {
    id: "community-inosuke-1361-video",
    productId: "nendoroid-1361",
    title: "No.1361 가품 언박싱 영상",
    summary: "영상 제목에서 No.1361 하시비라 이노스케를 가품·부트렉으로 명시하고 실물 개봉 과정을 보여주는 사례입니다.",
    images: ["https://i.ytimg.com/vi/bR_gqZKmOPc/hqdefault.jpg"],
    signals: [
      { evidenceKey: "boxFront", label: "영상에서 No.1361 패키지를 확인" },
      { evidenceKey: "figureFull", label: "가품으로 소개된 본체 실물을 확인" },
    ],
    sourceName: "YouTube 가품 언박싱",
    sourceUrl: "https://www.youtube.com/watch?v=bR_gqZKmOPc",
    sourcePublishedAt: null,
    caseKind: "specimen",
    confidenceLevel: "medium",
    verificationStatus: "author_asserted_video",
    evidenceSummary: "영상 작성자가 No.1361 가품 언박싱임을 명시했습니다.",
    ...communityDefaults,
  },
  {
    id: "community-gojo-1528-seller-mention",
    productId: "nendoroid-1528",
    title: "No.1528 가품으로 분류된 판매점 게시물",
    summary: "해외 판매점 게시물에 `NENDOROID 1528 GOJO SATORU FAKE`라고 등록된 사례입니다. 동일 모델 정품과의 직접 비교 자료는 아닙니다.",
    images: [],
    signals: [
      { evidenceKey: "figureFull", label: "판매점이 No.1528 실물을 가품으로 분류" },
    ],
    sourceName: "해외 판매점 게시물",
    sourceUrl: "https://www.facebook.com/FMSHOPVNHK/posts/pfbid02usSQoSrkdzE1NMzVRfuxJTrCxsshohpjEWDmyuQ8DwtHim9zAHoW6vP4b2nz1tJ5l",
    sourcePublishedAt: null,
    caseKind: "mention",
    confidenceLevel: "medium",
    verificationStatus: "community_catalog_asserted",
    evidenceSummary: "판매점의 가품 분류 문구는 확인했지만 동일 모델 비교 사진은 확인되지 않았습니다.",
    ...communityDefaults,
  },
  {
    id: "community-power-1580-author-mention",
    productId: "nendoroid-1580",
    title: "작성자가 가품이라고 명시한 No.1580",
    summary: "덴지 정품·가품 비교 글의 작성자가 마지막 사진 속 파워도 가품이라고 명시했습니다. No.1580 정품과의 직접 비교는 없습니다.",
    images: [
      "https://preview.redd.it/wd3sb9sqbw9c1.jpg?width=1080&crop=smart&auto=webp&s=606c9ffd5e002753e1afe13df3c8df4fba31fee9",
    ],
    signals: [
      { evidenceKey: "figureFull", label: "작성자가 사진 속 파워를 가품이라고 명시" },
    ],
    sourceName: "Reddit 작성자 언급",
    sourceUrl: "https://www.reddit.com/r/Nendoroid/comments/18w75br/spot_the_difference/",
    sourcePublishedAt: "2024-01-01",
    caseKind: "mention",
    confidenceLevel: "medium",
    verificationStatus: "author_asserted",
    evidenceSummary: "작성자의 가품 명시는 확인되지만 No.1580만의 정품·가품 비교 자료는 아닙니다.",
    ...communityDefaults,
  },
  {
    id: "community-sukuna-1834-video",
    productId: "nendoroid-1834",
    title: "No.1834 박스와 실물을 보여주는 가품 영상",
    summary: "국내 비교 영상에서 No.1834 박스와 본체를 가품으로 소개합니다. 영상의 직접 비교 대상은 고죠 No.1528이므로 스쿠나 동일 모델 비교로 보지는 않습니다.",
    images: [],
    signals: [
      { evidenceKey: "boxFront", label: "영상에서 No.1834 박스를 확인" },
      { evidenceKey: "figureFull", label: "영상에서 가품으로 소개된 스쿠나 실물을 확인" },
    ],
    sourceName: "Instagram 실물 비교 영상",
    sourceUrl: "https://www.instagram.com/reel/DUwgeflk1WR/",
    sourcePublishedAt: null,
    caseKind: "specimen",
    confidenceLevel: "medium",
    verificationStatus: "author_asserted_video",
    evidenceSummary: "스쿠나 실물은 확인되지만 비교 대상이 다른 모델이라 동일 모델 정품 비교 근거는 아닙니다.",
    ...communityDefaults,
  },
  {
    id: "community-hitori-2069-video-cross-source",
    productId: "nendoroid-2069",
    title: "No.2069 가품 실물 리뷰와 판매점 등록",
    summary: "가품으로 소개한 별도 언박싱·리뷰 영상과 제품 번호를 포함한 해외 판매점 게시물이 함께 확인된 사례입니다.",
    images: ["https://i.ytimg.com/vi/hvYwExim_og/hqdefault.jpg"],
    signals: [
      { evidenceKey: "boxFront", label: "영상에서 No.2069 패키지와 제품을 확인" },
      { evidenceKey: "figureFull", label: "가품으로 소개된 고토 히토리 실물을 확인" },
    ],
    sourceName: "YouTube 가품 리뷰",
    sourceUrl: "https://www.youtube.com/watch?v=hvYwExim_og",
    sourcePublishedAt: null,
    caseKind: "specimen",
    confidenceLevel: "medium",
    verificationStatus: "cross_source_author_asserted",
    evidenceSummary: "영상과 별도 판매점 게시물에서 같은 제품 번호의 가품 분류를 교차 확인했습니다.",
    secondarySources: [
      {
        name: "판매점 등록",
        url: "https://www.facebook.com/FMSHOPVNHK/posts/pfbid02usSQoSrkdzE1NMzVRfuxJTrCxsshohpjEWDmyuQ8DwtHim9zAHoW6vP4b2nz1tJ5l",
      },
    ],
    ...communityDefaults,
  },
  {
    id: "community-frieren-2367-ambiguous-comparison",
    productId: "nendoroid-2367",
    title: "No.2367 Real vs Fake 비교 게시물",
    summary: "게시물 제목과 사진에서 No.2367 두 제품 비교는 확인되지만, 본문에서 어느 쪽이 가품인지 명확히 설명하지 않아 검수 전 참고자료로만 표시합니다.",
    images: ["https://i.redd.it/2fe6tvb9fvag1.jpeg"],
    signals: [
      { evidenceKey: "figureFull", label: "동일 모델로 보이는 두 본체가 한 사진에 함께 있음" },
      { evidenceKey: "figureFull", label: "정품·가품 방향은 원문에서 명시되지 않음" },
    ],
    sourceName: "Reddit 비교 게시물",
    sourceUrl: "https://www.reddit.com/r/Frieren/comments/1q1q3nz/real_vs_fake_nendroid_frieren_2367/",
    sourcePublishedAt: "2026-01-02",
    caseKind: "mention",
    confidenceLevel: "medium",
    verificationStatus: "review_required",
    evidenceSummary: "제품 번호와 비교 사진은 확인되지만 가품 방향이 불명확합니다.",
    ...communityDefaults,
  },
];
